// Plotter module: app.js
// Generated by modularization of index.html inline script.

    let data = null;
    let selectedVars = [];
    let plotType = 'time-series';
    let timeSeriesMode = 'separate'; // 'merged' | 'separate'
    let separateAutoScale = true; // Y-axis auto-scale in separate mode
    let restoreZoom = null; // { start, end } — preserved dataZoom state across re-renders
    let chartInstance = null;
    let dragCounter = 0;
    // ===================== Binary Columns =====================
    let binaryColumns = new Set();      // column names detected as binary
    let binaryBits = new Map();         // column name → bit count (8 or 16)
    let binaryMode = new Map();         // column name → 'dec' | 'bin'

    // ===================== DOM Elements =====================
    const app = document.getElementById('app');
    const mainArea = document.getElementById('mainArea');
    const emptyState = document.getElementById('emptyState');
    const dragOverlay = document.getElementById('dragOverlay');
    const fileInput = document.getElementById('fileInput');
    const importBtn = document.getElementById('importBtn');
    const emptyImportBtn = document.getElementById('emptyImportBtn');
    const fileName = document.getElementById('fileName');
    const errorBanner = document.getElementById('errorBanner');
    const errorText = document.getElementById('errorText');
    const errorClose = document.getElementById('errorClose');
    const themeToggle = document.getElementById('themeToggle');
    const themeIcon = document.getElementById('themeIcon');

    function debounce(fn, delay) {
      let timer = null;
      function debounced(...args) {
        clearTimeout(timer);
        timer = setTimeout(() => fn.apply(this, args), delay);
      }
      debounced.cancel = () => { clearTimeout(timer); timer = null; };
      return debounced;
    }
    // ===================== Version Check =====================
    const CURRENT_VERSION = 'v1.2.3';
    let latestVersion = null; // set when a newer version is found

    function compareVersions(a, b) {
      // Parse semver strings like 'v1.1.2' or '1.1.2'
      const parse = (v) => v.replace(/^v/, '').split('.').map(Number);
      const pa = parse(a), pb = parse(b);
      for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
        const na = pa[i] || 0, nb = pb[i] || 0;
        if (na !== nb) return na - nb;
      }
      return 0;
    }

    async function checkVersion() {
      try {
        const resp = await fetch('https://api.github.com/repos/cyren2019/plotter/releases/latest', {
          signal: AbortSignal.timeout(5000)
        });
        if (resp.ok) {
          const data = await resp.json();
          const remote = data.tag_name || '';
          if (remote && compareVersions(remote, CURRENT_VERSION) > 0) {
            latestVersion = remote;
          }
        }
      } catch (_) {
        // Silently ignore — offline, rate-limited, etc.
      }
      updateVersionBadges();
    }

    function updateVersionBadges() {
      const releasesUrl = 'https://github.com/cyren2019/plotter/releases';
      const badges = document.querySelectorAll('.version-badge');
      badges.forEach(badge => {
        if (latestVersion) {
          badge.classList.add('has-update');
          badge.title = t('new_version', { v: latestVersion });
          if (!badge.textContent.includes('→')) {
            badge.textContent = `${CURRENT_VERSION} → ${latestVersion}`;
          }
          badge.onclick = () => window.open(releasesUrl, '_blank');
        } else {
          badge.classList.remove('has-update');
          badge.title = '';
          badge.textContent = CURRENT_VERSION;
          badge.onclick = null;
        }
      });
    }

    // ===================== Theme =====================
    let isDark = false;
    function applyTheme(dark) {
      isDark = dark;
      if (dark) {
        document.documentElement.setAttribute('data-theme', 'dark');
        themeIcon.innerHTML = '<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>';
      } else {
        document.documentElement.removeAttribute('data-theme');
        themeIcon.innerHTML = '<circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>';
      }
    }
    themeToggle.addEventListener('click', () => {
      applyTheme(!isDark);
      if (data) renderChart();
    });
    const langToggle = document.getElementById('langToggle');
    langToggle.addEventListener('click', () => {
      setLanguage(currentLang === 'zh' ? 'en' : 'zh');
    });

    // ===================== Error Handling =====================
    function getThemeColors() {
      return isDark
        ? { bg: '#111827', text: '#d1d5db', textMuted: '#9ca3af', heading: '#f9fafb',
            splitLine: '#374151', axisLine: '#999', gridBg: 'rgba(255,255,255,0.03)',
            gridBorder: '#374151', yLabel: '#d1d5db', xLabel: '#d1d5db', subplotLabel: '#9ca3af' }
        : { bg: '#ffffff', text: '#333', textMuted: '#999', heading: '#111827',
            splitLine: '#eee', axisLine: '#999', gridBg: 'rgba(128,128,128,0.05)',
            gridBorder: '#e5e7eb', yLabel: '#333', xLabel: '#666', subplotLabel: '#888' };
    }
    function showError(msg) {
      errorText.textContent = msg;
      errorBanner.style.display = 'flex';
    }
    function hideError() {
      errorBanner.style.display = 'none';
    }
    errorClose.addEventListener('click', hideError);

    // ===================== File Import =====================
    async function processFile(file) {
      hideError();
      const ext = file.name.split('.').pop().toLowerCase();
      if (!['csv', 'xls', 'xlsx', 'log', 'txt'].includes(ext)) {
        showError(t('unsupported_format') + file.name);
        return;
      }
      try {
        const parsed = await parseFile(file);
        data = parsed;
        // Detect binary columns
        const { cols, bits } = detectBinaryColumns(parsed.headers, parsed.rows, parsed.timeColumn);
        binaryColumns = cols;
        binaryBits = bits;
        binaryMode = new Map();
        for (const col of cols) {
          binaryMode.set(col, 'dec');
        }
        // Cache value ranges per column (used in non-auto-scale separate mode)
        data.valueRanges = computeValueRanges(parsed);
        fileName.textContent = file.name;
        const nonTime = parsed.headers.filter(h => h !== parsed.timeColumn);
        selectedVars = nonTime.slice(0, 3);
        plotType = 'time-series';
        renderApp();
      } catch (err) {
        showError(err.message || t('parse_failed'));
      }
    }

    importBtn.addEventListener('click', () => fileInput.click());
    emptyImportBtn.addEventListener('click', () => fileInput.click());
    fileInput.addEventListener('change', (e) => {
      const file = e.target.files?.[0];
      if (file) processFile(file);
      e.target.value = '';
    });

    // ===================== Drag & Drop =====================
    app.addEventListener('dragenter', (e) => {
      e.preventDefault(); e.stopPropagation();
      dragCounter++;
      if (e.dataTransfer.items?.length > 0) dragOverlay.style.display = 'flex';
    });
    app.addEventListener('dragover', (e) => { e.preventDefault(); e.stopPropagation(); });
    app.addEventListener('dragleave', (e) => {
      e.preventDefault(); e.stopPropagation();
      dragCounter--;
      if (dragCounter <= 0) { dragCounter = 0; dragOverlay.style.display = 'none'; }
    });
    app.addEventListener('drop', (e) => {
      e.preventDefault(); e.stopPropagation();
      dragOverlay.style.display = 'none';
      dragCounter = 0;
      const file = e.dataTransfer.files?.[0];
      if (file) processFile(file);
    });

    function setBinaryMode(varName, mode) {
      // Auto-select variable if not already selected
      if (!selectedVars.includes(varName)) {
        const maxSelectable = getMaxSelectable();
        if (selectedVars.length < maxSelectable) {
          selectedVars.push(varName);
        } else {
          return; // max reached, do nothing
        }
      }
      binaryMode.set(varName, mode);
      // Preserve zoom state before targeted re-render
      saveZoomState();
      // Targeted update: toggle the single var-item state + re-render chart
      updateSingleVarItemState(varName);
      updateSelectedCountBadge();
      updateChartMsg();
      renderChart();
    }

    // Global resize (debounced)
    const debouncedResize = debounce(() => {
      if (chartInstance) chartInstance.resize();
    }, 100);
    window.addEventListener('resize', debouncedResize);

    // Kick off version check
    checkVersion();
    updateStaticTexts();
