// Plotter module: chart-render.js
// Generated by modularization of index.html inline script.

    function escapeHtml(str) {
      return String(str).replace(/[&<>"']/g, s => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[s]));
    }
    // Find the TIME-axis dataZoom (xAxisIndex 1) in an ECharts option — the slider
    // carries the current time-window selection. Spectrum zooms (xAxisIndex 0) are
    // visual only and must never be mistaken for the time window.
    function getTimeDataZoom(opt) {
      if (!opt || !opt.dataZoom) return null;
      const isTimeAxis = (d) => (d.xAxisIndex === 1) || (Array.isArray(d.xAxisIndex) && d.xAxisIndex.includes(1));
      return opt.dataZoom.find(d => isTimeAxis(d) && d.type === 'slider') || opt.dataZoom.find(isTimeAxis) || null;
    }
    function saveZoomState() {
      if (chartInstance && !restoreZoom) {
        try {
          const dz = getTimeDataZoom(chartInstance.getOption());
          if (dz) {
            restoreZoom = { start: dz.start, end: dz.end };
          }
        } catch (e) { /* ignore */ }
      }
    }
    function computeValueRanges(parsed) {
      const ranges = {};
      for (const h of parsed.headers) {
        if (h === parsed.timeColumn) continue;
        let min = Infinity, max = -Infinity;
        for (const row of parsed.rows) {
          const v = row[h];
          if (v === null || v === undefined || isNaN(Number(v)) || !isFinite(Number(v))) continue;
          const n = Number(v);
          if (n < min) min = n;
          if (n > max) max = n;
        }
        if (min !== Infinity) {
          ranges[h] = { min, max };
        }
      }
      return ranges;
    }
    function getBinToggleTitle(varName, binDisabled) {
      if (binDisabled) return t('bin_disabled');
      const mode = binaryMode.get(varName) || 'dec';
      return mode === 'bin' ? t('bin_toggle_dec') : t('bin_toggle_bin');
    }
    // ===================== Render App =====================
    let activeFilterFn = null; // track current debounced filter for cancellation
    function renderApp() {
      // Cancel any pending debounced search filter from previous render
      if (activeFilterFn && activeFilterFn.cancel) activeFilterFn.cancel();
      activeFilterFn = null;

      if (!data) {
        mainArea.innerHTML = '';
        mainArea.appendChild(emptyState);
        emptyState.style.display = 'flex';
        return;
      }
      emptyState.style.display = 'none';

      // Preserve zoom state across variable selection / mode changes
      if (chartInstance && !restoreZoom) {
        try {
          const dz = getTimeDataZoom(chartInstance.getOption());
          if (dz) {
            restoreZoom = { start: dz.start, end: dz.end };
          }
        } catch (e) { /* ignore */ }
      }

      // Preserve search value and scroll position before re-rendering
      const oldSearchInput = document.querySelector('.search-box input');
      const savedSearchValue = oldSearchInput ? oldSearchInput.value : '';
      const oldVarList = document.getElementById('varList');
      const savedScrollTop = oldVarList ? oldVarList.scrollTop : 0;

      const sidebar = document.createElement('aside');
      sidebar.className = 'sidebar';

      const vars = data.headers.filter(h => h !== data.timeColumn);
      const searchId = 'varSearch' + Date.now();

      sidebar.innerHTML = `
        <div class="sidebar-header">
          <div class="title-row">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" y1="22" x2="4" y2="15"/></svg>
            <span>${t('var_select')}</span>
          </div>
          <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
            <div class="search-box" style="flex: 1; margin-bottom: 0;">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
              <input type="text" id="${searchId}" placeholder="${t('search_placeholder')}">
            </div>
            <button class="btn" id="deselectAllBtn" style="flex-shrink: 0;">${t('deselect_all')}</button>
          </div>
          <div class="selected-count">
            <span class="badge ${selectedVars.length === 0 ? 'empty' : ''}">${selectedVars.length}</span>
            <span>/ ${vars.length} ${t('var_count')}</span>
            ${(() => {
              const max = getMaxSelectable();
              if (max !== Infinity) {
                return `<span style="opacity:0.5">${t('max_limit', { n: max })}</span>`;
              }
              return '';
            })()}
          </div>
          <div class="var-limit-toast" id="varLimitToast"></div>
        </div>
        <div class="var-list" id="varList"></div>
      `;

      const varList = sidebar.querySelector('#varList');

      // Time row
      const timeRow = document.createElement('div');
      timeRow.className = 'time-row';
      const selectId = 'timeColumnSelect' + Date.now();
      const options = data.headers.map(h =>
        `<option value="${h}" ${h === data.timeColumn ? 'selected' : ''}>${h}</option>`
      ).join('');
      timeRow.innerHTML = `
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
        <select class="time-select" id="${selectId}">
          ${options}
        </select>
      `;
      varList.appendChild(timeRow);

      const timeSelect = timeRow.querySelector('#' + selectId);
      timeSelect.addEventListener('change', (e) => {
        const newTimeColumn = e.target.value;
        if (newTimeColumn === data.timeColumn) return;

        // Remove new time column from selected vars if present
        if (selectedVars.includes(newTimeColumn)) {
          selectedVars = selectedVars.filter(v => v !== newTimeColumn);
        }

        // Re-process rows with new time column
        data.rows = processRows(data.headers, data.rawRows, newTimeColumn);
        data.timeColumn = newTimeColumn;
        data.timeFormat = detectColumnFormat(newTimeColumn, data.rows);
        // Recompute value ranges (old time column is now a data column)
        data.valueRanges = computeValueRanges(data);

        renderApp();
      });

      function renderVars(filter = '') {
        const filtered = filter.trim()
          ? vars.filter(v => v.toLowerCase().includes(filter.toLowerCase().trim()))
          : vars;

        // Remove existing var items and empty messages
        varList.querySelectorAll('.var-item, .var-empty').forEach(el => el.remove());

        if (filtered.length === 0 && vars.length > 0) {
          const empty = document.createElement('div');
          empty.className = 'var-empty';
          empty.style.cssText = 'padding: 40px 16px; text-align: center; font-size: 12px; color: var(--text); opacity: 0.3;';
          empty.textContent = t('no_match');
          varList.appendChild(empty);
          return;
        }

        filtered.forEach(v => {
          const item = document.createElement('div');
          const isSelected = selectedVars.includes(v);
          const isBinary = binaryColumns.has(v);
          const binMode = isBinary ? (binaryMode.get(v) || 'dec') : null;
          const binDisabled = plotType !== 'time-series' || timeSeriesMode === 'merged';

          item.className = 'var-item' + (isSelected ? ' selected' : '') + (binMode === 'bin' ? ' bin-active' : '');
          if (isBinary) item.setAttribute('data-binary', '');

          // Build right-side content (binary dot + toggle)
          let rightContent = '';
          if (isBinary) {
            const disabledAttr = binDisabled ? 'disabled' : '';
            const activeClass = binMode === 'bin' ? 'active' : '';
            const titleText = getBinToggleTitle(v, binDisabled);
            rightContent = `
              <button class="bin-toggle ${activeClass}" ${disabledAttr} title="${titleText}">BIN</button>
            `;
          }

          item.innerHTML = `
            <div class="checkbox">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3"><polyline points="20 6 9 17 4 12"/></svg>
            </div>
            <span class="name" title="${escapeHtml(v)}">${escapeHtml(v)}</span>
            ${rightContent}
          `;
          item.addEventListener('click', () => {
            if (selectedVars.includes(v)) {
              selectedVars = selectedVars.filter(s => s !== v);
            } else {
              const max = getMaxSelectable();
              if (selectedVars.length >= max) {
                const toast = sidebar.querySelector('#varLimitToast');
                if (toast) {
                  const modeKey = plotType === 'time-series' ? 'time_series' : plotType === 'xy' ? 'xy_plot' : 'xyz_plot';
                  toast.textContent = t('msg_var_limit', { mode: t(modeKey), n: max });
                  toast.style.display = 'block';
                  clearTimeout(toast._hideTimer);
                  toast._hideTimer = setTimeout(() => { toast.style.display = 'none'; }, 2000);
                }
                return;
              }
              selectedVars.push(v);
            }
            // Preserve zoom state before targeted re-render
            saveZoomState();
            // Targeted update: toggle class, update badge, re-render chart only
            item.classList.toggle('selected', selectedVars.includes(v));
            updateSelectedCountBadge();
            updateChartMsg();
            renderChart();
          });
          // Attach binary toggle event listener (toggle on click)
          if (isBinary) {
            const binBtn = item.querySelector('.bin-toggle');
            if (binBtn) {
              binBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                if (!binBtn.disabled) {
                  // Read current mode from global state (not closure, which is stale after targeted updates)
                  const currentMode = binaryMode.get(v) || 'dec';
                  const newMode = currentMode === 'bin' ? 'dec' : 'bin';
                  setBinaryMode(v, newMode);
                }
              });
            }
          }
          varList.appendChild(item);
        });
      }

      renderVars();

      // CSS visibility-based search filter (no DOM recreation)
      const applyVarFilter = (filterText) => {
        const lower = filterText.toLowerCase().trim();
        const items = varList.querySelectorAll('.var-item');
        let visibleCount = 0;
        items.forEach(item => {
          const nameEl = item.querySelector('.name');
          const name = nameEl ? nameEl.textContent : '';
          const visible = !lower || name.toLowerCase().includes(lower);
          item.style.display = visible ? '' : 'none';
          if (visible) visibleCount++;
        });
        // Show/hide "no matching variables" message
        let emptyEl = varList.querySelector('.var-empty');
        if (visibleCount === 0 && items.length > 0) {
          if (!emptyEl) {
            emptyEl = document.createElement('div');
            emptyEl.className = 'var-empty';
            emptyEl.style.cssText = 'padding: 40px 16px; text-align: center; font-size: 12px; color: var(--text); opacity: 0.3;';
            emptyEl.textContent = t('no_match');
            varList.appendChild(emptyEl);
          }
          emptyEl.style.display = '';
        } else if (emptyEl) {
          emptyEl.style.display = 'none';
        }
      };
      const filterVarItems = debounce(applyVarFilter, 150);
      activeFilterFn = filterVarItems;
      sidebar.querySelector('#' + searchId).addEventListener('input', (e) => {
        filterVarItems(e.target.value);
      });

      sidebar.querySelector('#deselectAllBtn').addEventListener('click', () => {
        selectedVars = [];
        for (const col of binaryColumns) {
          binaryMode.set(col, 'dec');
        }
        // Preserve zoom state before targeted re-render
        saveZoomState();
        // Clear all .selected and .bin-active classes on existing DOM
        varList.querySelectorAll('.var-item').forEach(el => {
          el.classList.remove('selected', 'bin-active');
          const toggle = el.querySelector('.bin-toggle');
          if (toggle) toggle.classList.remove('active');
        });
        updateSelectedCountBadge();
        updateChartMsg();
        renderChart();
      });

      const plotSection = document.createElement('section');
      plotSection.className = 'plot-section';

      const tsToggleVisible = plotType === 'time-series';
      plotSection.innerHTML = `
        <nav class="plot-tabs">
          <button class="btn ${plotType === 'time-series' ? 'active' : ''}" data-type="time-series">${t('time_series')}</button>
          <button class="btn ${plotType === 'xy' ? 'active' : ''}" data-type="xy">${t('xy_plot')}</button>
          <button class="btn ${plotType === 'xyz' ? 'active' : ''}" data-type="xyz">${t('xyz_plot')}</button>
          <button class="btn ${plotType === 'fft' ? 'active' : ''}" data-type="fft">${t('fft_plot')}</button>
          <div style="display: ${(tsToggleVisible || plotType === 'fft') ? 'flex' : 'none'}; align-items: center; gap: 4px; margin-left: auto;">
            <div class="ts-toggle" data-ts="auto-scale" style="display: ${timeSeriesMode === 'separate' && plotType !== 'fft' ? 'flex' : 'none'}">
              <button class="btn ${separateAutoScale ? 'active' : ''}" data-auto-scale="toggle">${t('auto_scale')}</button>
            </div>
            <div class="ts-toggle">
              <button class="btn" data-reset="zoom">${t('reset_zoom')}</button>
            </div>
            <div class="ts-toggle" style="display: ${plotType === 'fft' ? 'none' : ''}">
              <button class="btn ${timeSeriesMode === 'merged' ? 'active' : ''}" data-mode="merged">${t('merged')}</button>
              <button class="btn ${timeSeriesMode === 'separate' ? 'active' : ''}" data-mode="separate">${t('separate')}</button>
            </div>
          </div>
        </nav>
        <div class="fft-panel" style="display: ${plotType === 'fft' ? 'flex' : 'none'};">
          <div class="fft-panel-row">
            <label class="fft-label">
              <span>${t('fft_window')}</span>
              <select class="fft-select" id="fftWindowSelect">
                <option value="rect" ${fftWindow === 'rect' ? 'selected' : ''}>${t('win_rect')}</option>
                <option value="hann" ${fftWindow === 'hann' ? 'selected' : ''}>${t('win_hann')}</option>
                <option value="hamming" ${fftWindow === 'hamming' ? 'selected' : ''}>${t('win_hamming')}</option>
                <option value="blackman" ${fftWindow === 'blackman' ? 'selected' : ''}>${t('win_blackman')}</option>
                <option value="blackmanHarris" ${fftWindow === 'blackmanHarris' ? 'selected' : ''}>${t('win_blackman_harris')}</option>
                <option value="flattop" ${fftWindow === 'flattop' ? 'selected' : ''}>${t('win_flattop')}</option>
                <option value="kaiser" ${fftWindow === 'kaiser' ? 'selected' : ''}>${t('win_kaiser')}</option>
              </select>
            </label>
          </div>
          <div class="fft-panel-row">
            <label class="fft-label">
              <span>${t('fft_freq_unit')}</span>
              <select class="fft-select" id="fftFreqUnitSelect">
                <option value="Hz" ${fftFreqUnit === 'Hz' ? 'selected' : ''}>Hz</option>
                <option value="rad/s" ${fftFreqUnit === 'rad/s' ? 'selected' : ''}>rad/s</option>
                <option value="deg/s" ${fftFreqUnit === 'deg/s' ? 'selected' : ''}>deg/s</option>
                <option value="rpm" ${fftFreqUnit === 'rpm' ? 'selected' : ''}>rpm</option>
              </select>
            </label>
            <label class="fft-label">
              <span>${t('fft_y_axis')}</span>
              <div class="fft-segmented">
                <button class="fft-seg-btn ${fftYAxis === 'physical' ? 'active' : ''}" data-fft-param="yAxis" data-value="physical">${t('fft_physical')}</button>
                <button class="fft-seg-btn ${fftYAxis === 'per-unit' ? 'active' : ''}" data-fft-param="yAxis" data-value="per-unit">${t('fft_per_unit')}</button>
                <button class="fft-seg-btn ${fftYAxis === 'db' ? 'active' : ''}" data-fft-param="yAxis" data-value="db">${t('fft_db')}</button>
              </div>
            </label>
            <label class="fft-label">
              <span>${t('fft_amp')}</span>
              <div class="fft-segmented">
                <button class="fft-seg-btn ${fftAmpUnit === 'pk' ? 'active' : ''}" data-fft-param="ampUnit" data-value="pk">${t('amp_pk')}</button>
                <button class="fft-seg-btn ${fftAmpUnit === 'rms' ? 'active' : ''}" data-fft-param="ampUnit" data-value="rms">${t('amp_rms')}</button>
              </div>
            </label>
            <label class="fft-label">
              <span>${t('fft_x_axis')}</span>
              <div class="fft-segmented">
                <button class="fft-seg-btn ${fftXAxis === 'linear' ? 'active' : ''}" data-fft-param="xAxis" data-value="linear">${t('fft_linear')}</button>
                <button class="fft-seg-btn ${fftXAxis === 'log' ? 'active' : ''}" data-fft-param="xAxis" data-value="log">${t('fft_log')}</button>
              </div>
            </label>
            <label class="fft-label">
              <span>${t('fft_avg')}</span>
              <div class="fft-segmented">
                <button class="fft-seg-btn ${fftAveraging === 'none' ? 'active' : ''}" data-fft-param="averaging" data-value="none">${t('avg_none')}</button>
                <button class="fft-seg-btn ${fftAveraging === 'linear' ? 'active' : ''}" data-fft-param="averaging" data-value="linear">${t('avg_linear')}</button>
                <button class="fft-seg-btn ${fftAveraging === 'exp' ? 'active' : ''}" data-fft-param="averaging" data-value="exp">${t('avg_exp')}</button>
                <button class="fft-seg-btn ${fftAveraging === 'peak' ? 'active' : ''}" data-fft-param="averaging" data-value="peak">${t('avg_peak')}</button>
              </div>
            </label>
            <span class="fft-nyquist-hint" id="fftNyquistHint"></span>
            <button class="btn btn-primary" id="fftApplyBtn">${t('fft_apply')}</button>
          </div>
        </div>
        <div class="fft-measurements" id="fftMeasurements" style="display: none;">
          <span class="fft-mstat"><b>${t('meas_f0')}</b><i id="mF0">-</i></span>
          <span class="fft-mstat"><b>THD</b><i id="mTHD">-</i></span>
          <span class="fft-mstat"><b>THD+N</b><i id="mTHDN">-</i></span>
          <span class="fft-mstat"><b>SNR</b><i id="mSNR">-</i></span>
          <span class="fft-mstat"><b>SFDR</b><i id="mSFDR">-</i></span>
          <span class="fft-mstat"><b>SINAD</b><i id="mSINAD">-</i></span>
          <span class="fft-mstat"><b>${t('meas_noise')}</b><i id="mNoise">-</i></span>
        </div>
        <div class="plot-label"><span>${getModeLabel()}</span></div>
        <div class="plot-container">
          <div id="chart"></div>
          <div class="chart-msg" id="chartMsg"></div>
        </div>
      `;

      plotSection.querySelectorAll('.plot-tabs .btn[data-type]').forEach(btn => {
        btn.addEventListener('click', () => {
          plotType = btn.dataset.type;
          // Reset binary mode to dec when switching to merged mode
          if (plotType === 'time-series' && timeSeriesMode === 'merged') {
            for (const col of binaryColumns) {
              binaryMode.set(col, 'dec');
            }
          }
          // Cleanup FFT handler when switching away
          if (plotType !== 'fft') {
            if (fftDataZoomHandler && fftDataZoomHandler.cancel) fftDataZoomHandler.cancel();
            fftDataZoomHandler = null;
            if (chartInstance) chartInstance.off('datazoom');
            fftDataZoomStart = 0;
            fftDataZoomEnd = 100;
          }
          const max = getMaxSelectable();
          if (selectedVars.length > max) {
            selectedVars = selectedVars.slice(0, max);
          }
          renderApp();
        });
      });

      plotSection.querySelectorAll('.ts-toggle .btn[data-mode]').forEach(btn => {
        btn.addEventListener('click', () => {
          timeSeriesMode = btn.dataset.mode;
          // Reset binary mode to dec when switching to merged mode
          if (timeSeriesMode === 'merged') {
            for (const col of binaryColumns) {
              binaryMode.set(col, 'dec');
            }
          }
          // Update active button states inline
          const toggle = btn.closest('.ts-toggle');
          if (toggle) {
            toggle.querySelectorAll('.btn[data-mode]').forEach(b => {
              b.classList.toggle('active', b.dataset.mode === timeSeriesMode);
            });
          }
          // Show/hide auto-scale button (use data attribute, not positional selector)
          const autoScaleToggle = plotSection.querySelector('.ts-toggle[data-ts="auto-scale"]');
          if (autoScaleToggle) {
            autoScaleToggle.style.display = timeSeriesMode === 'separate' ? 'flex' : 'none';
          }
          // Update bin controls enabled/disabled state
          updateBinControlsState();
          // Update mode label
          const label = plotSection.querySelector('.plot-label span');
          if (label) label.textContent = getModeLabel();
          // Preserve zoom state before re-render
          saveZoomState();
          renderChart();
        });
      });

      const autoScaleBtn = plotSection.querySelector('.btn[data-auto-scale]');
      if (autoScaleBtn) {
        autoScaleBtn.addEventListener('click', () => {
          separateAutoScale = !separateAutoScale;
          autoScaleBtn.classList.toggle('active', separateAutoScale);
          // Preserve zoom position across auto-scale toggle
          if (chartInstance) {
            const dz = getTimeDataZoom(chartInstance.getOption());
            if (dz) {
              restoreZoom = { start: dz.start, end: dz.end };
            }
          }
          renderChart();
        });
      }

      const resetZoomBtn = plotSection.querySelector('.btn[data-reset="zoom"]');
      if (resetZoomBtn) {
        resetZoomBtn.addEventListener('click', () => {
          if (chartInstance) {
            chartInstance.dispatchAction({
              type: 'dataZoom',
              start: 0,
              end: 100,
            });
          }
        });
      }

      // FFT parameter panel event handlers
      const fftPanel = plotSection.querySelector('.fft-panel');
      if (fftPanel) {
        // Segmented button groups
        const applyFftParam = (param, value) => {
          if (param === 'yAxis') fftYAxis = value;
          else if (param === 'xAxis') fftXAxis = value;
          else if (param === 'averaging') fftAveraging = value;
          else if (param === 'ampUnit') fftAmpUnit = value;
        };
        fftPanel.querySelectorAll('.fft-seg-btn[data-fft-param]').forEach(btn => {
          btn.addEventListener('click', () => {
            applyFftParam(btn.dataset.fftParam, btn.dataset.value);
            const group = btn.closest('.fft-segmented');
            if (group) {
              group.querySelectorAll('.fft-seg-btn').forEach(b => b.classList.remove('active'));
            }
            btn.classList.add('active');
          });
        });

        // Window function select
        const fftWindowSelect = fftPanel.querySelector('#fftWindowSelect');
        if (fftWindowSelect) {
          fftWindowSelect.addEventListener('change', () => {
            if (FFT_WINDOWS[fftWindowSelect.value]) fftWindow = fftWindowSelect.value;
          });
        }

        // Frequency unit dropdown
        const fftFreqUnitSelect = fftPanel.querySelector('#fftFreqUnitSelect');
        if (fftFreqUnitSelect) {
          fftFreqUnitSelect.addEventListener('change', () => {
            fftFreqUnit = fftFreqUnitSelect.value;
          });
        }

        // Apply button — triggers FFT recompute with current params
        const fftApplyBtn = fftPanel.querySelector('#fftApplyBtn');
        if (fftApplyBtn) {
          fftApplyBtn.addEventListener('click', () => {
            // Re-read DOM values to ensure they're synced (all segmented params)
            fftPanel.querySelectorAll('.fft-seg-btn.active[data-fft-param]').forEach(b => {
              applyFftParam(b.dataset.fftParam, b.dataset.value);
            });
            const winSelect = fftPanel.querySelector('#fftWindowSelect');
            if (winSelect && FFT_WINDOWS[winSelect.value]) fftWindow = winSelect.value;
            const freqUnitSelect = fftPanel.querySelector('#fftFreqUnitSelect');
            if (freqUnitSelect) fftFreqUnit = freqUnitSelect.value;
            // Re-render chart with new params
            saveZoomState();
            renderChart();
          });
        }
      }

      mainArea.innerHTML = '';
      mainArea.appendChild(sidebar);

      const resizer = document.createElement('div');
      resizer.className = 'resizer';
      mainArea.appendChild(resizer);

      let isResizing = false;
      resizer.addEventListener('mousedown', (e) => {
        isResizing = true;
        resizer.classList.add('dragging');
        document.body.style.cursor = 'col-resize';
        document.body.style.userSelect = 'none';
        const startX = e.clientX;
        const startWidth = sidebar.offsetWidth;

        function onMouseMove(e) {
          if (!isResizing) return;
          const newWidth = Math.min(Math.max(180, startWidth + (e.clientX - startX)), window.innerWidth / 2);
          document.documentElement.style.setProperty('--sidebar-width', newWidth + 'px');
          if (chartInstance) requestAnimationFrame(() => chartInstance.resize());
        }

        function onMouseUp() {
          isResizing = false;
          resizer.classList.remove('dragging');
          document.body.style.cursor = '';
          document.body.style.userSelect = '';
          document.removeEventListener('mousemove', onMouseMove);
          document.removeEventListener('mouseup', onMouseUp);
        }

        document.addEventListener('mousemove', onMouseMove);
        document.addEventListener('mouseup', onMouseUp);
      });

      mainArea.appendChild(plotSection);

      // Restore search value and re-filter using CSS visibility (preserves all DOM elements)
      const newSearchInput = sidebar.querySelector('#' + searchId);
      if (newSearchInput && savedSearchValue) {
        newSearchInput.value = savedSearchValue;
        applyVarFilter(savedSearchValue);
      }

      // Restore scroll position of var-list after re-rendering
      const newVarList = sidebar.querySelector('#varList');
      if (newVarList && savedScrollTop > 0) {
        newVarList.scrollTop = savedScrollTop;
      }

      requestAnimationFrame(() => renderChart());
    }

    function getModeLabel() {
      switch (plotType) {
        case 'time-series': return t('mode_ts');
        case 'xy': return t('mode_xy');
        case 'xyz': return t('mode_xyz');
        case 'fft': return t('mode_fft');
        default: return '';
      }
    }

    function getMaxSelectable() {
      if (plotType === 'time-series') return 10;
      if (plotType === 'xy') return 2;
      if (plotType === 'xyz') return 3;
      if (plotType === 'fft') return 1;
      return Infinity;
    }

    // ===================== Targeted UI Helpers =====================
    // Lightweight DOM updates that avoid a full renderApp() rebuild.

    function updateSelectedCountBadge() {
      const badge = document.querySelector('.selected-count .badge');
      if (!badge) return;
      badge.textContent = selectedVars.length;
      badge.classList.toggle('empty', selectedVars.length === 0);
    }

    function updateChartMsg() {
      const msgEl = document.getElementById('chartMsg');
      if (!msgEl) return;
      const msg = getChartMessage();
      if (msg) {
        msgEl.style.display = 'flex';
        let p = msgEl.querySelector('p');
        if (!p) { p = document.createElement('p'); msgEl.appendChild(p); }
        p.textContent = msg;
      } else {
        msgEl.style.display = 'none';
      }
    }

    function updateSingleVarItemState(varName) {
      const items = document.querySelectorAll('.var-item');
      items.forEach(el => {
        const nameEl = el.querySelector('.name');
        if (nameEl && nameEl.textContent === varName) {
          el.classList.toggle('selected', selectedVars.includes(varName));
          const isBin = binaryColumns.has(varName);
          const binMode = isBin ? (binaryMode.get(varName) || 'dec') : null;
          el.classList.toggle('bin-active', binMode === 'bin');
          const btn = el.querySelector('.bin-toggle');
          if (btn) {
            btn.classList.toggle('active', binMode === 'bin');
            const binDisabled = plotType !== 'time-series' || timeSeriesMode === 'merged';
            btn.disabled = binDisabled;
            btn.title = getBinToggleTitle(varName, binDisabled);
          }
        }
      });
    }

    function updateBinControlsState() {
      const items = document.querySelectorAll('.var-item[data-binary]');
      const binDisabled = plotType !== 'time-series' || timeSeriesMode === 'merged';
      items.forEach(el => {
        const btn = el.querySelector('.bin-toggle');
        const varName = el.querySelector('.name')?.textContent || '';
        if (btn) {
          btn.disabled = binDisabled;
          btn.title = getBinToggleTitle(varName, binDisabled);
        }
      });
    }

    // ===================== Chart Rendering =====================
    function renderChart() {
      const container = document.getElementById('chart');
      const msgEl = document.getElementById('chartMsg');
      if (!container || !data) return;

      // Lazy-init chart instance: reuse if exists and still in the DOM,
      // re-create if renderApp() rebuilt the DOM (old canvas destroyed)
      let isNewInstance = false;
      if (!chartInstance || !document.contains(chartInstance.getDom())) {
        if (chartInstance) {
          try { chartInstance.dispose(); } catch (e) { /* ignore */ }
          chartInstance = null;
        }
        if (!container.parentElement) return;
        chartInstance = echarts.init(container);
        isNewInstance = true;
      }

      const msg = getChartMessage();
      if (msg) {
        // Clear chart canvas so old data doesn't show behind the message
        if (chartInstance) {
          try { chartInstance.clear(); } catch (e) { /* ignore */ }
        }
        msgEl.style.display = 'flex';
        msgEl.querySelector('p')?.remove();
        const p = document.createElement('p');
        p.textContent = msg;
        msgEl.appendChild(p);
        return;
      }
      msgEl.style.display = 'none';

      // Pre-set container height before setOption to ensure correct canvas size
      // Must match constants in buildTimeSeriesOption() separate mode
      if (plotType === 'time-series' && timeSeriesMode === 'separate') {
        const varsToPlot = selectedVars.slice(0, 10);
        const rowHeight = 200, rowHeightBit = 25, labelHeight = 10, gap = 20, topPad = 8, bottomGap = 8;
        let totalHeight = topPad;
        for (let i = 0; i < varsToPlot.length; i++) {
          const v = varsToPlot[i];
          const isBinVar = binaryColumns.has(v) && binaryMode.get(v) === 'bin';
          const bitCount = isBinVar ? (binaryBits.get(v) || 8) : 0;
          totalHeight += isBinVar ? (bitCount * rowHeightBit) : rowHeight;
          totalHeight += labelHeight;
          if (i < varsToPlot.length - 1) totalHeight += gap;
        }
        totalHeight += bottomGap;
        container.style.height = totalHeight + 'px';
      } else {
        container.style.height = '100%';
      }

      chartInstance.resize(); // ensure canvas matches container size

      // Double-click to reset zoom (attach once)
      if (isNewInstance) {
        chartInstance.on('dblclick', () => {
          chartInstance.dispatchAction({
            type: 'dataZoom',
            start: 0,
            end: 100,
          });
        });
      }

      let option;
      switch (plotType) {
        case 'time-series': option = buildTimeSeriesOption(); break;
        case 'xy': option = buildXYOption(); break;
        case 'xyz': option = buildXYZOption(); break;
        case 'fft': option = buildFFTOption(); break;
      }

      if (option) {
        try {
          chartInstance.setOption(option, true);
        } catch (e) {
          console.warn('ECharts render warning:', e.message);
        }
        requestAnimationFrame(() => chartInstance && chartInstance.resize());
      }

      // Global resize handler (single, persistent — no per-render listener needed)
    }

    function getChartMessage() {
      if (plotType === 'time-series' && selectedVars.length === 0) return t('msg_select_var');
      if (plotType === 'xy' && selectedVars.length < 2) return t('msg_xy_need');
      if (plotType === 'xyz' && selectedVars.length < 3) return t('msg_xyz_need');
      if (plotType === 'fft' && selectedVars.length === 0) return t('msg_fft_need');
      return null;
    }

    const BIT_COLORS = [
      '#3b82f6', '#22c55e', '#f59e0b', '#ef4444',
      '#8b5cf6', '#06b6d4', '#ec4899', '#84cc16',
    ];

    const SAMPLING_THRESHOLD = 10000; // apply LTTB sampling when data exceeds 10k rows

    function getBitColor(bit) {
      return BIT_COLORS[bit % BIT_COLORS.length];
    }

    function buildTimeSeriesOption() {
      const { rows, timeColumn } = data;
      const timeLabels = rows.map(row => {
        const val = row[timeColumn];
        if (val instanceof Date) return dayjs(val).format('YYYY-MM-DD HH:mm:ss');
        return String(val ?? '');
      });

      const formatTooltipTime = (dataIndex) => {
        const val = rows[dataIndex]?.[timeColumn];
        if (val instanceof Date) return dayjs(val).format('YYYY-MM-DD HH:mm:ss.SSS');
        return timeLabels[dataIndex] ?? '';
      };

      const varsToPlot = selectedVars.slice(0, 10);

      // Preserve zoom state across re-renders
      const zoomStart = restoreZoom ? restoreZoom.start : 0;
      const zoomEnd = restoreZoom ? restoreZoom.end : 100;
      restoreZoom = null;

      // Merged mode: all series in one chart, shared Y-axis
      if (timeSeriesMode === 'merged') {
        const tc = getThemeColors();
        const series = varsToPlot.map(variable => ({
          name: variable,
          type: 'line',
          data: rows.map(row => {
            const val = row[variable];
            if (val === null || val === undefined) return null;
            return Number(val);
          }),
          symbol: 'none',
          sampling: rows.length > SAMPLING_THRESHOLD ? 'lttb' : undefined,
        }));

        return {
          backgroundColor: isDark ? tc.bg : 'transparent',
          tooltip: {
            trigger: 'axis',
            formatter: (params) => {
              const title = formatTooltipTime(params[0]?.dataIndex);
              return title + '<br/>' + params.map(p => p.marker + ' ' + p.seriesName + ': ' + (p.value ?? '-')).join('<br/>');
            },
          },
          legend: { type: 'scroll', bottom: 0, textStyle: { fontSize: 12, color: tc.text } },
          grid: {
            left: '3%', right: '4%',
            bottom: varsToPlot.length > 5 ? '15%' : '10%',
            top: '3%', containLabel: true,
          },
          xAxis: {
            type: 'category', data: timeLabels,
            axisLabel: { rotate: timeLabels.length > 20 ? 45 : 0, fontSize: 11, color: tc.text },
            axisLine: { lineStyle: { color: tc.axisLine } },
          },
          yAxis: {
            type: 'value',
            name: varsToPlot.length === 1 ? varsToPlot[0] : '',
            nameTextStyle: { fontSize: 11, color: tc.text },
            axisLabel: { color: tc.text },
            splitLine: { lineStyle: { color: tc.splitLine } },
          },
          series,
          dataZoom: [
            { type: 'slider', start: zoomStart, end: zoomEnd, bottom: varsToPlot.length > 5 ? '8%' : '4%', borderColor: tc.splitLine, fillerColor: isDark ? 'rgba(59,130,246,0.2)' : 'rgba(59,130,246,0.1)', handleStyle: { color: tc.axisLine }, textStyle: { color: tc.text } },
            { type: 'inside', start: zoomStart, end: zoomEnd },
          ],
        };
      }

       // Separate mode: one subplot per variable (or per bit for binary vars)
      // Calculate total rows and bit layout
      const varLayout = []; // { variable, isBinVar, bitCount, rowCount }
      for (const variable of varsToPlot) {
        const isBinVar = binaryColumns.has(variable) && binaryMode.get(variable) === 'bin';
        const bitCount = isBinVar ? (binaryBits.get(variable) || 8) : 0;
        const rowCount = isBinVar ? bitCount : 1;
        varLayout.push({ variable, isBinVar, bitCount, rowCount });
      }

      const rowHeight = 200;
      // Binary block height: 8bit → 200px, 16bit → 400px (25px per bit)
      const rowHeightBit = 25;
      const gap = 20;
      const topPad = 8;
      const labelHeight = 10;
      const bottomGap = 8;

      const grids = [];
      const graphics = [];
      const xAxes = [];
      const yAxes = [];
      const series = [];

      const tc = getThemeColors();

      // Fixed left margin for strict alignment across all subplots
      const gridLeft = 60;
      const gridRight = 30;

      let rowIndex = 0;
      let cumulativeTop = topPad;

      for (let varIdx = 0; varIdx < varLayout.length; varIdx++) {
        const { variable, isBinVar, bitCount, rowCount } = varLayout[varIdx];
        if (isBinVar) {
          // Bits from top to bottom: bitN-1 → bit0
          for (let bitRow = bitCount - 1; bitRow >= 0; bitRow--) {
            const gridTop = cumulativeTop;

            grids.push({
              top: gridTop,
              left: gridLeft,
              right: gridRight,
              height: rowHeightBit,
              containLabel: false,
              show: true,
              borderColor: tc.gridBorder,
              borderWidth: 1,
              backgroundColor: tc.gridBg,
            });

            xAxes.push({
              type: 'category',
              data: timeLabels,
              gridIndex: rowIndex,
              axisLine: { show: false },
              axisTick: { show: false },
              axisLabel: { show: false },
              axisPointer: { show: true, type: 'line', lineStyle: { color: '#4f46e5', width: 2 } },
              position: 'bottom',
            });

            yAxes.push({
              type: 'value',
              gridIndex: rowIndex,
              show: true,
              name: `bit${bitRow}`,
              nameLocation: 'center',
              nameGap: 15,
              nameRotate: 0,
              nameTextStyle: {
                fontSize: 10,
                color: tc.subplotLabel,
              },
              axisLine: { show: false },
              axisTick: { show: false },
              axisLabel: {
                show: true,
                formatter: value => value === 0 ? '0' : '',
                fontSize: 10,
                color: tc.subplotLabel,
                margin: 2,
              },
              splitLine: { show: false },
              min: 0,
              max: 1.2,
              scale: false,
            });

            series.push({
              name: `${variable} · bit${bitRow}`,
              type: 'line',
              data: rows.map(row => {
                const val = Number(row[variable]);
                if (val === null || val === undefined || isNaN(val) || !isFinite(val)) return null;
                return (val >> bitRow) & 1;
              }),
              symbol: 'none',
              lineStyle: { width: 1.5 },
              xAxisIndex: rowIndex,
              yAxisIndex: rowIndex,
              itemStyle: { color: getBitColor(bitRow) },
              sampling: rows.length > SAMPLING_THRESHOLD ? 'lttb' : undefined,
            });

            cumulativeTop += rowHeightBit;
            rowIndex++;
          }

          // Variable name label below the bit block (same as decimal)
          graphics.push({
            type: 'text',
            left: 'center',
            top: cumulativeTop + 4,
            style: {
              text: variable,
              fill: tc.subplotLabel,
              font: 'bold 12px sans-serif',
            },
          });

          // Gap between variable blocks (not after the last one)
          if (varIdx < varLayout.length - 1) {
            cumulativeTop += gap;
          }
        } else {
          // Decimal: existing logic
          const gridTop = cumulativeTop;

          grids.push({
            top: gridTop,
            left: gridLeft,
            right: gridRight,
            height: rowHeight,
            containLabel: false,
            show: true,
            borderColor: tc.gridBorder,
            borderWidth: 1,
            backgroundColor: tc.gridBg,
          });

          xAxes.push({
            type: 'category',
            data: timeLabels,
            gridIndex: rowIndex,
            axisLine: { show: false },
            axisTick: { show: false },
            axisLabel: { show: false },
            axisPointer: { show: true, type: 'line', lineStyle: { color: '#4f46e5', width: 2 } },
            position: 'bottom',
          });

          const yAxisConfig = {
            type: 'value',
            gridIndex: rowIndex,
            show: true,
            axisLine: { show: true, onZero: false, lineStyle: { color: tc.axisLine } },
            axisTick: { show: true, lineStyle: { color: tc.axisLine } },
            axisLabel: { show: true, color: tc.subplotLabel, fontSize: 10, formatter: v => Number(v).toFixed(1) },
            splitLine: { show: true, lineStyle: { color: tc.splitLine, type: 'dashed' } },
          };

          if (separateAutoScale) {
            yAxisConfig.scale = true;
          } else {
            const range = data.valueRanges && data.valueRanges[variable];
            if (range) {
              const padding = (range.max - range.min) * 0.1;
              if (padding === 0) {
                yAxisConfig.min = range.min - 1;
                yAxisConfig.max = range.max + 1;
              } else {
                yAxisConfig.min = range.min - padding;
                yAxisConfig.max = range.max + padding;
              }
            } else {
              yAxisConfig.min = 0;
              yAxisConfig.max = 1;
            }
          }

          yAxes.push(yAxisConfig);

          series.push({
            name: variable,
            type: 'line',
            data: rows.map(row => {
              const val = row[variable];
              if (val === null || val === undefined || isNaN(Number(val)) || !isFinite(Number(val))) return null;
              return Number(val);
            }),
            symbol: 'none',
            xAxisIndex: rowIndex,
            yAxisIndex: rowIndex,
            lineStyle: { width: 1.5 },
            sampling: rows.length > SAMPLING_THRESHOLD ? 'lttb' : undefined,
          });

          // Variable name label below
          graphics.push({
            type: 'text',
            left: 'center',
            top: gridTop + rowHeight + 4,
            style: {
              text: variable,
              fill: tc.subplotLabel,
              font: 'bold 12px sans-serif',
            },
          });

          cumulativeTop += rowHeight;
          rowIndex++;

          // Gap between variable blocks (not after the last one)
          if (varIdx < varLayout.length - 1) {
            cumulativeTop += gap;
          }
        }
      }

      // All X axis indices for dataZoom synchronization
      const allXAxisIndices = Array.from({ length: rowIndex }, (_, idx) => idx);

      return {
        backgroundColor: tc.bg,
        tooltip: {
          show: true,
          trigger: 'axis',
          axisPointer: { type: 'line', lineStyle: { color: '#ff0000', width: 3 } },
          formatter: (params) => {
            const idx = params[0]?.dataIndex;
            const title = idx != null ? formatTooltipTime(idx) : '';
            // Binary bit series: show all bits with hovered bit highlighted
            const bitMatch = params[0]?.seriesName?.match(/^(.+) · bit(\d+)$/);
            if (bitMatch && idx != null) {
              const varName = bitMatch[1];
              const hoveredBit = parseInt(bitMatch[2], 10);
              const row = rows[idx];
              const rawVal = row ? Number(row[varName]) : 0;
              const val = (rawVal === null || rawVal === undefined || isNaN(rawVal) || !isFinite(rawVal)) ? 0 : rawVal;
              let lines = title + '<br/><span style="font-weight:bold;color:#4f46e5">' + varName + ' = ' + val + '</span>';
              const bitCount = binaryBits.get(varName) || 8;
              for (let b = bitCount - 1; b >= 0; b--) {
                const bitVal = (val >> b) & 1;
                const color = getBitColor(b);
                const marker = '<span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:' + color + ';vertical-align:middle;margin-right:4px;"></span>';
                const label = marker + 'bit' + b + ': ' + bitVal;
                lines += b === hoveredBit
                  ? '<br/><span style="font-weight:bold;font-size:13px">' + label + '</span>'
                  : '<br/><span style="opacity:0.5">' + label + '</span>';
              }
              return lines;
            }
            return title + '<br/>' + params.map(p => p.marker + ' ' + p.seriesName + ': ' + (p.value ?? '-')).join('<br/>');
          },
        },
        graphic: graphics,
        grid: grids,
        xAxis: xAxes,
        yAxis: yAxes,
        series,
        animation: false,
        dataZoom: [
          {
            type: 'inside',
            xAxisIndex: allXAxisIndices,
            start: zoomStart,
            end: zoomEnd,
          },
        ],
      };
    }

    function buildXYOption() {
      const xVar = selectedVars[0];
      const yVar = selectedVars[1];
      const scatterData = data.rows
        .map(row => {
          const x = row[xVar];
          const y = row[yVar];
          if (x === null || x === undefined || y === null || y === undefined) return null;
          return [Number(x), Number(y)];
        })
        .filter(d => d !== null);

      const tc = getThemeColors();
      return {
        backgroundColor: isDark ? tc.bg : 'transparent',
        tooltip: {
          trigger: 'item',
          formatter: (params) => `${xVar}: ${params.data[0]}<br/>${yVar}: ${params.data[1]}`,
        },
        grid: { left: '3%', right: '4%', bottom: '3%', top: '3%', containLabel: true },
        xAxis: { type: 'value', name: xVar, nameLocation: 'center', nameGap: 25, nameTextStyle: { fontSize: 11, color: tc.text }, axisLabel: { color: tc.text }, splitLine: { lineStyle: { color: tc.splitLine } } },
        yAxis: { type: 'value', name: yVar, nameLocation: 'center', nameGap: 30, nameRotate: 90, nameTextStyle: { fontSize: 11, color: tc.text }, axisLabel: { color: tc.text }, splitLine: { lineStyle: { color: tc.splitLine } } },
        series: [{ type: 'scatter', data: scatterData, symbolSize: 4 }],
      };
    }

    function buildXYZOption() {
      const xVar = selectedVars[0];
      const yVar = selectedVars[1];
      const zVar = selectedVars[2];
      const rawData = data.rows
        .map(row => {
          const x = row[xVar];
          const y = row[yVar];
          const z = row[zVar];
          if (x === null || x === undefined || y === null || y === undefined || z === null || z === undefined) return null;
          return [Number(x), Number(y), Number(z)];
        })
        .filter(d => d !== null);

      const tc = getThemeColors();
      return {
        backgroundColor: isDark ? tc.bg : 'transparent',
        tooltip: {
          formatter: (params) => `${xVar}: ${params.data[0]}<br/>${yVar}: ${params.data[1]}<br/>${zVar}: ${params.data[2]}`,
        },
        xAxis3D: { type: 'value', name: xVar, nameTextStyle: { fontSize: 11, color: tc.text }, axisLabel: { color: tc.text } },
        yAxis3D: { type: 'value', name: yVar, nameTextStyle: { fontSize: 11, color: tc.text }, axisLabel: { color: tc.text } },
        zAxis3D: { type: 'value', name: zVar, nameTextStyle: { fontSize: 11, color: tc.text }, axisLabel: { color: tc.text } },
        grid3D: {
          boxWidth: 200, boxDepth: 80,
          viewControl: { autoRotate: false },
          light: { main: { intensity: isDark ? 0.8 : 1.2 } },
        },
        series: [{
          type: 'scatter3D',
          data: rawData,
          symbolSize: 4,
          itemStyle: { opacity: 0.8 },
        }],
      };
    }

    function getFftYAxisName() {
      if (fftYAxis === 'per-unit') return t('fft_per_unit');
      if (fftYAxis === 'db') return t('fft_db');
      if (fftAmpUnit === 'rms') return t('amp_rms_label');
      return t('fft_physical');
    }

    // Bar width = 80% of one frequency bin, in the display unit. Computed from the
    // Hz bin resolution so the rendered pixel width stays identical across frequency
    // units (switching between units must not change the bar thickness).
    function getFftBarWidth(binResolutionHz, freqUnit) {
      const factor = getFreqUnitFactor(freqUnit);
      // Clamp the Hz-equivalent width so thin bars stay visible (unit-invariant)
      const hzWidth = Math.max(binResolutionHz * 0.8, 0.2);
      return hzWidth * factor;
    }

    let fftMeasurements = null; // latest auto-measurement results (drives the measurement strip)

    function renderFftMeasurements() {
      const box = document.getElementById('fftMeasurements');
      if (!box) return;
      const set = (id, txt) => { const el = document.getElementById(id); if (el) el.textContent = txt; };
      if (!fftMeasurements) {
        box.style.display = 'none';
        return;
      }
      box.style.display = 'flex';
      const m = fftMeasurements;
      const f0 = m.fundamental.freq;
      const f0Label = (f0 * getFreqUnitFactor(fftFreqUnit)).toFixed(2) + ' ' + fftFreqUnit;
      const fmtDb = (v) => (v === Infinity || v === -Infinity) ? '∞' : (Number.isFinite(v) ? v.toFixed(1) + ' dB' : '-');
      set('mF0', f0Label);
      set('mTHD', m.thd.pct.toFixed(2) + '%');
      set('mTHDN', m.thdn.pct.toFixed(2) + '%');
      set('mSNR', fmtDb(m.snr));
      set('mSFDR', fmtDb(m.sfdr));
      set('mSINAD', fmtDb(m.sinad));
      set('mNoise', Number.isFinite(m.noiseFloor) ? m.noiseFloor.toFixed(1) + ' dBc' : '∞');
    }

    function buildFFTOption() {
      const { rows, timeColumn } = data;
      const varName = selectedVars[0];
      const tc = getThemeColors();

      // Preserve the spectrum frequency-axis zoom across re-renders
      let specZoomStart = 0, specZoomEnd = 100;
      if (chartInstance) {
        try {
          const prev = chartInstance.getOption();
          const isSpec = (d) => (d.xAxisIndex === 0) || (Array.isArray(d.xAxisIndex) && d.xAxisIndex.includes(0));
          const sdz = prev && prev.dataZoom ? prev.dataZoom.find(isSpec) : null;
          if (sdz) { specZoomStart = sdz.start || 0; specZoomEnd = sdz.end || 100; }
        } catch (e) { /* ignore */ }
      }

      // Determine data range from zoom state
      const zoomStart = restoreZoom ? restoreZoom.start : fftDataZoomStart;
      const zoomEnd = restoreZoom ? restoreZoom.end : fftDataZoomEnd;
      restoreZoom = null;
      // Keep the change-detection tracking in sync with the rendered time slider
      fftDataZoomStart = zoomStart;
      fftDataZoomEnd = zoomEnd;

      const startIdx = Math.floor(rows.length * zoomStart / 100);
      const endIdx = Math.min(Math.ceil(rows.length * zoomEnd / 100), rows.length);
      const clampedStart = Math.max(0, startIdx);
      const clampedEnd = Math.min(rows.length, Math.max(clampedStart + 2, endIdx));

      // Compute sample rate and FFT (sample rate always auto-detected)
      const srInfo = detectSampleRate(rows, timeColumn);
      const sampleRate = srInfo.sampleRate;
      const fftResult = computeAveragedFFT(rows, varName, clampedStart, clampedEnd, sampleRate, fftWindow, fftAveraging);

      // Build frequency axis and magnitude data
      let freqData = [];
      let magData = [];
      // Harmonic markLines
      let markLines = [];
      let autoDetectedF0 = null;
      let f0confidence = 'unknown';
      fftMeasurements = null;

      if (fftResult) {
        // Fundamental frequency: auto-detected (no manual override)
        const detected = autoDetectBaseFreq(fftResult.magnitudes, fftResult.freqs, sampleRate, fftResult.fftSize);
        const baseFreq = detected.freq;
        f0confidence = detected.confidence || 'unknown';
        autoDetectedF0 = baseFreq;

        // Auto-measurements (THD / THD+N / SNR / SFDR / SINAD / noise floor)
        fftMeasurements = computeMeasurements(fftResult.magnitudes, fftResult.freqs, sampleRate, fftResult.fftSize, baseFreq);

        // Use the corrected frequency axis from FFT result
        const convertedFreqs = convertFreqUnit(fftResult.freqs, fftFreqUnit);

        let magnitudes = fftResult.magnitudes;

        // --- Amplitude unit calibration (applied before display transform) ---
        if (fftAmpUnit === 'rms') {
          // RMS: peak/√2 (DC stays as-is)
          const scaled = new Float64Array(magnitudes.length);
          for (let i = 0; i < magnitudes.length; i++) {
            scaled[i] = i === 0 ? magnitudes[i] : magnitudes[i] / Math.SQRT2;
          }
          magnitudes = scaled;
        }
        // 'pk': leave as coherent-gain-compensated peak magnitudes

        // --- Y-axis display transform ---
        if (fftYAxis === 'per-unit') {
          // Per-unit: normalize to max magnitude, excluding DC (index 0)
          let maxMag = 0;
          for (let i = 1; i < magnitudes.length; i++) {
            if (magnitudes[i] > maxMag) maxMag = magnitudes[i];
          }
          if (maxMag > 0) {
            const scaled = new Float64Array(magnitudes.length);
            for (let i = 0; i < magnitudes.length; i++) scaled[i] = magnitudes[i] / maxMag;
            magnitudes = scaled;
          }
        } else if (fftYAxis === 'db') {
          // dB: 20*log10(magnitude), referenced to max (excluding DC)
          let refMag = 1.0;
          for (let i = 1; i < magnitudes.length; i++) {
            if (magnitudes[i] > refMag) refMag = magnitudes[i];
          }
          const dbFloor = -120;
          const converted = new Float64Array(magnitudes.length);
          for (let i = 0; i < magnitudes.length; i++) {
            const val = magnitudes[i] / refMag;
            converted[i] = val > 1e-10 ? 20 * Math.log10(val) : dbFloor;
          }
          magnitudes = converted;
        }

        // Harmonic markLines at f0, 2f0, 3f0... up to Nyquist (max 20)
        const nyquistLimit = sampleRate / 2;
        const f0 = baseFreq;
        for (let h = 1; h <= 20; h++) {
          const harmonicFreq = h * f0;
          if (harmonicFreq > nyquistLimit * 0.99) break;
          const displayFreq = harmonicFreq * getFreqUnitFactor(fftFreqUnit);
          markLines.push({
            xAxis: displayFreq,
            lineStyle: { type: 'dashed', color: h === 1 ? 'rgba(239,68,68,0.5)' : 'rgba(156,163,175,0.25)', width: h === 1 ? 1.5 : 0.5 },
            label: { show: h === 1, formatter: h + '×', position: 'start', color: 'rgba(239,68,68,0.7)', fontSize: 10 },
          });
        }

        freqData = Array.from(convertedFreqs);
        magData = Array.from(magnitudes);
      }

      // Time labels for preview
      const timeLabels = rows.map(row => {
        const val = row[timeColumn];
        if (val instanceof Date) return dayjs(val).format('YYYY-MM-DD HH:mm:ss');
        return String(val ?? '');
      });

      // Time-series data for preview
      const tsData = rows.map(row => {
        const val = row[varName];
        if (val === null || val === undefined) return null;
        return Number(val);
      });

      const freqUnitLabel = fftFreqUnit;

      const option = {
        backgroundColor: isDark ? tc.bg : 'transparent',
        tooltip: {
          trigger: 'axis',
          axisPointer: { type: 'cross' },
          // Note the x-axis frequency unit in the spectrum tooltip (x-axis name label is hidden)
          formatter: (params) => {
            const arr = Array.isArray(params) ? params : [params];
            const unit = freqUnitLabel;
            return arr.map(p => {
              const name = p.seriesName || '';
              if (name.endsWith('FFT')) {
                const v = p.value;
                const x = Array.isArray(v) ? v[0] : p.axisValue;
                const y = Array.isArray(v) ? v[1] : v;
                const xStr = (typeof x === 'number' && isFinite(x)) ? x.toFixed(3) + ' ' + unit : String(x);
                const yStr = (typeof y === 'number' && isFinite(y)) ? y.toFixed(3) : String(y);
                return p.marker + ' ' + name + '<br/>' + xStr + '<br/>' + getFftYAxisName() + ': ' + yStr;
              }
              const y = Array.isArray(p.value) ? p.value[1] : p.value;
              return p.marker + ' ' + name + ': ' + (y != null ? y : '-');
            }).join('<br/>');
          },
        },
        grid: [
          // Spectrum fills the space above the fixed-height time preview
          {
            left: '3%', right: '4%', top: 30, bottom: 280,
            containLabel: true,
          },
          // Time preview: fixed 200px height (matches time-series single panel)
          {
            left: '3%', right: '4%', bottom: 40, height: 200,
            containLabel: true,
          },
        ],
        xAxis: [
          {
            type: fftXAxis === 'log' ? 'log' : 'value',
            axisLabel: { color: tc.text, fontSize: 10 },
            splitLine: { lineStyle: { color: tc.splitLine } },
            gridIndex: 0,
            min: fftXAxis === 'log' ? Math.max(freqData[1] || 0.001, 0.001) : 0,
          },
          {
            type: 'category',
            data: timeLabels,
            axisLabel: { show: false },
            axisLine: { lineStyle: { color: tc.axisLine } },
            gridIndex: 1,
          },
        ],
        yAxis: [
          {
            type: 'value',
            name: getFftYAxisName(),
            nameLocation: 'middle',
            nameGap: 30,
            nameTextStyle: { fontSize: 11, color: tc.text },
            axisLabel: { color: tc.text, fontSize: 10 },
            splitLine: { lineStyle: { color: tc.splitLine } },
            gridIndex: 0,
          },
          {
            type: 'value',
            name: varName,
            nameLocation: 'middle',
            nameGap: 30,
            nameTextStyle: { fontSize: 11, color: tc.text },
            axisLabel: { color: tc.text, fontSize: 10 },
            splitLine: { lineStyle: { color: tc.splitLine } },
            gridIndex: 1,
          },
        ],
        series: [
          {
            name: varName + ' FFT',
            type: 'bar',
            data: freqData.map((f, i) => [f, magData[i]]),
            xAxisIndex: 0,
            yAxisIndex: 0,
            barWidth: getFftBarWidth(fftResult.binResolution, fftFreqUnit),
            itemStyle: { color: '#5470c6' }, // match time-series mode palette[0]
            sampling: freqData.length > SAMPLING_THRESHOLD ? 'lttb' : undefined,
            markLine: markLines.length > 0 ? {
              silent: true,
              symbol: 'none',
              data: markLines,
            } : undefined,
          },
          {
            name: varName,
            type: 'line',
            data: tsData,
            xAxisIndex: 1,
            yAxisIndex: 1,
            symbol: 'none',
            lineStyle: { width: 1.5 },
            itemStyle: { color: '#5470c6' }, // match time-series mode palette[0]
            sampling: rows.length > SAMPLING_THRESHOLD ? 'lttb' : undefined,
          },
        ],
        dataZoom: [
          // Spectrum frequency-axis zoom (visual only — does not trigger FFT recompute)
          {
            type: 'slider',
            xAxisIndex: 0,
            start: specZoomStart,
            end: specZoomEnd,
            bottom: 247,
            borderColor: tc.splitLine,
            fillerColor: isDark ? 'rgba(59,130,246,0.2)' : 'rgba(59,130,246,0.1)',
            handleStyle: { color: tc.axisLine },
            textStyle: { color: tc.text },
          },
          {
            type: 'inside',
            xAxisIndex: 0,
            start: specZoomStart,
            end: specZoomEnd,
          },
          // Time-window selection (drives FFT recompute)
          {
            type: 'slider',
            xAxisIndex: 1,
            start: zoomStart,
            end: zoomEnd,
            bottom: 5,
            borderColor: tc.splitLine,
            fillerColor: isDark ? 'rgba(59,130,246,0.2)' : 'rgba(59,130,246,0.1)',
            handleStyle: { color: tc.axisLine },
            textStyle: { color: tc.text },
          },
          {
            type: 'inside',
            xAxisIndex: 1,
            start: zoomStart,
            end: zoomEnd,
          },
        ],
      };

      // Attach dataZoom event for real-time FFT update.
      // Recompute the FFT for the newly selected time window via a full re-render
      // (buildFFTOption). A full render guarantees the spectrum is drawn exactly as
      // on the initial render — incremental setOption merges can leave stale
      // markLines / partial canvas state, producing an incorrect spectrum.
      if (fftDataZoomHandler) {
        chartInstance.off('datazoom', fftDataZoomHandler);
        if (fftDataZoomHandler.cancel) fftDataZoomHandler.cancel();
      }
      fftDataZoomHandler = debounce(() => {
        if (!chartInstance || plotType !== 'fft') return;
        const opt = chartInstance.getOption();
        const timeDZ = getTimeDataZoom(opt);
        if (!timeDZ) return;
        const start = timeDZ.start || 0;
        const end = timeDZ.end || 100;
        // Only recompute when the time window actually changed. Spectrum-axis zooms
        // (xAxisIndex 0) leave the time window untouched and are purely visual.
        if (Math.abs(start - fftDataZoomStart) < 0.01 && Math.abs(end - fftDataZoomEnd) < 0.01) return;
        fftDataZoomStart = start;
        fftDataZoomEnd = end;
        restoreZoom = null; // buildFFTOption must use the tracked time window
        renderChart();
      }, 150);
      chartInstance.on('datazoom', fftDataZoomHandler);

      // Update the hint to show sample rate and auto-detected f0
      const hint = document.querySelector('#fftNyquistHint');
      if (hint) {
        let parts = [];
        parts.push('fs=' + sampleRate.toFixed(1) + ' Hz');
        if (autoDetectedF0 !== null) {
          parts.push('f₀=' + autoDetectedF0.toFixed(2) + ' Hz');
          if (f0confidence === 'low' || f0confidence === 'unknown') parts.push('⚠');
        }
        if (srInfo.confidence !== 'high') parts.push('⚠');
        hint.textContent = parts.join(' ');
      }

      renderFftMeasurements();
      return option;
    }
