// Plotter module: fft.js
// Generated by modularization of index.html inline script.

    // ===================== FFT State =====================
    let fftBaseFreq = null;           // null = auto-detect from time data
    let fftFreqUnit = 'Hz';           // 'Hz' | 'rad/s' | 'deg/s'
    let fftYAxis = 'per-unit';        // 'per-unit' | 'physical' | 'db'
    let fftXAxis = 'linear';          // 'linear' | 'log'
    let fftSampleRateOverride = null; // null = auto-detect; number = manual override (Hz)
    let fftDataZoomStart = 0;         // current dataZoom start percentage
    let fftDataZoomEnd = 100;         // current dataZoom end percentage
    let fftDataZoomHandler = null;    // debounced dataZoom event handler reference

    // ===================== FFT Computation =====================
    function nextPowerOf2(n) {
      if (n < 2) return 2;
      let p = 1;
      while (p < n) p <<= 1;
      return p;
    }

    function hannWindow(N) {
      const w = new Float64Array(N);
      for (let i = 0; i < N; i++) {
        w[i] = 0.5 * (1 - Math.cos((2 * Math.PI * i) / (N - 1)));
      }
      return w;
    }

    function detectSampleRate(rows, timeColumn) {
      // Returns { sampleRate, confidence: 'high'|'low'|'unknown', method }
      let dateCount = 0, numericCount = 0, totalDelta = 0, deltaCount = 0;
      let prevDate = null, prevNumeric = null;
      const deltas = [];
      const maxSamples = Math.min(rows.length, 200);
      for (let i = 0; i < maxSamples; i++) {
        const val = rows[i][timeColumn];
        if (val instanceof Date) {
          dateCount++;
          if (prevDate !== null) {
            const delta = (val - prevDate) / 1000;
            if (delta > 0) { totalDelta += delta; deltaCount++; deltas.push(delta); }
          }
          prevDate = val;
        } else if (typeof val === 'number' && Number.isFinite(val)) {
          numericCount++;
          if (prevNumeric !== null) {
            const delta = val - prevNumeric;
            if (delta > 0) { totalDelta += delta; deltaCount++; deltas.push(delta); }
          }
          prevNumeric = val;
        } else if (val !== null && val !== undefined) {
          const n = Number(val);
          if (Number.isFinite(n)) {
            numericCount++;
            if (prevNumeric !== null) {
              const delta = n - prevNumeric;
              if (delta > 0) { totalDelta += delta; deltaCount++; deltas.push(delta); }
            }
            prevNumeric = n;
          }
        }
      }
      if (deltaCount > 0) {
        const avgDelta = totalDelta / deltaCount;
        const sr = 1 / avgDelta;
        let variance = 0;
        for (let i = 0; i < deltas.length; i++) variance += (deltas[i] - avgDelta) ** 2;
        const cv = Math.sqrt(variance / deltas.length) / avgDelta;
        const confidence = cv < 0.05 ? 'high' : cv < 0.3 ? 'low' : 'unknown';
        const method = dateCount > 0 ? 'date' : 'numeric';
        return { sampleRate: sr, confidence, method };
      }
      return { sampleRate: 1, confidence: 'unknown', method: 'fallback' };
    }

    function convertFreqUnit(freqs, unit) {
      if (unit === 'Hz') return freqs;
      const factor = unit === 'rad/s' ? 2 * Math.PI : unit === 'deg/s' ? 360 : 1;
      const result = new Float64Array(freqs.length);
      for (let i = 0; i < freqs.length; i++) result[i] = freqs[i] * factor;
      return result;
    }

    function computeFFT(rows, varName, startIdx, endIdx, sampleRate) {
      // Extract non-null values from the selected range
      const rawValues = [];
      for (let i = startIdx; i < endIdx && i < rows.length; i++) {
        const val = rows[i][varName];
        if (val !== null && val !== undefined && Number.isFinite(Number(val))) {
          rawValues.push(Number(val));
        }
      }

      if (rawValues.length < 2) return null;

      // Determine FFT size: next power of 2
      const fftSize = nextPowerOf2(rawValues.length);
      const window = hannWindow(rawValues.length);

      // Compute coherent gain for amplitude compensation
      let windowSum = 0;
      for (let i = 0; i < rawValues.length; i++) windowSum += window[i];
      const coherentGain = windowSum / rawValues.length;

      const padded = new Float64Array(fftSize);
      for (let i = 0; i < rawValues.length; i++) {
        padded[i] = rawValues[i] * window[i];
      }

      const rawMagnitudes = FourierTransform.rfft(padded);
      const numBins = rawMagnitudes.length;

      // Compensate for window coherent gain
      const magnitudes = new Float64Array(numBins);
      for (let i = 0; i < numBins; i++) {
        magnitudes[i] = rawMagnitudes[i] / coherentGain;
      }

      // Build correct frequency axis: f[i] = i * sampleRate / fftSize
      const binResolution = sampleRate / fftSize;
      const freqs = new Float64Array(numBins);
      for (let i = 0; i < numBins; i++) {
        freqs[i] = i * binResolution;
      }

      return {
        magnitudes: magnitudes,
        freqs: freqs,
        numBins: numBins,
        fftSize: fftSize,
        dataLength: rawValues.length,
        binResolution: binResolution,
      };
    }

    function autoDetectBaseFreq(magnitudes, freqs, sampleRate, fftSize) {
      // Find fundamental frequency using harmonic scoring.
      if (!magnitudes || magnitudes.length < 3) return { freq: sampleRate / fftSize, confidence: 'unknown' };

      const binResolution = sampleRate / fftSize;

      // Find all local maxima (skip DC at index 0)
      let maxMag = 0;
      const peaks = [];
      for (let i = 1; i < magnitudes.length - 1; i++) {
        if (magnitudes[i] > magnitudes[i - 1] && magnitudes[i] > magnitudes[i + 1]) {
          peaks.push({ index: i, mag: magnitudes[i], freq: freqs[i] });
          if (magnitudes[i] > maxMag) maxMag = magnitudes[i];
        }
      }

      if (peaks.length === 0) return { freq: binResolution, confidence: 'unknown' };

      const noiseFloor = maxMag * 0.1;
      const sigPeaks = peaks.filter(p => p.mag >= noiseFloor);

      if (sigPeaks.length === 0) {
        const best = peaks.reduce((a, b) => a.mag > b.mag ? a : b);
        return { freq: best.freq, confidence: 'low' };
      }

      // Harmonic scoring for each candidate
      let meanSpectrum = 0;
      for (let i = 0; i < magnitudes.length; i++) meanSpectrum += magnitudes[i];
      meanSpectrum /= magnitudes.length;

      const nyquist = sampleRate / 2;
      let bestCandidate = null, bestScore = -Infinity;

      for (const peak of sigPeaks) {
        const f0 = peak.freq;
        if (f0 < binResolution * 0.5) continue;
        let harmonicScore = peak.mag;
        let harmonicCount = 1;
        for (let h = 2; h <= 8; h++) {
          const harmonicFreq = h * f0;
          if (harmonicFreq > nyquist * 0.95) break;
          const binIdx = Math.round(harmonicFreq / binResolution);
          if (binIdx < magnitudes.length) {
            harmonicScore += magnitudes[binIdx];
            harmonicCount++;
          }
        }
        const avgHarmonicMag = harmonicScore / harmonicCount;
        const score = avgHarmonicMag / Math.max(meanSpectrum, 1e-10);
        if (score > bestScore) {
          bestScore = score;
          bestCandidate = { freq: f0, confidence: harmonicCount >= 2 ? 'high' : 'low', harmonicCount };
        }
      }

      if (bestCandidate) return bestCandidate;
      const best = sigPeaks.reduce((a, b) => a.mag > b.mag ? a : b);
      return { freq: best.freq, confidence: 'low' };
    }
