// Plotter module: fft.js
// Generated by modularization of index.html inline script.

    // ===================== FFT State =====================
    let fftFreqUnit = 'Hz';           // 'Hz' | 'rad/s' | 'deg/s' | 'rpm'
    let fftYAxis = 'per-unit';        // 'per-unit' | 'physical' | 'db'
    let fftXAxis = 'linear';          // 'linear' | 'log'
    let fftDataZoomStart = 0;         // current dataZoom start percentage
    let fftDataZoomEnd = 100;         // current dataZoom end percentage
    let fftDataZoomHandler = null;    // debounced dataZoom event handler reference
    let fftWindow = 'hann';           // window function (see FFT_WINDOWS registry)
    let fftAveraging = 'none';        // 'none' | 'linear' | 'exp' | 'peak'
    let fftAmpUnit = 'pk';            // 'pk' | 'rms' — amplitude calibration

    // ===================== Window Functions =====================
    // Window registry: name → { enbw (noise-equivalent bandwidth in bins), create(N) }.
    // enbw is used for PSD scaling. Formulas use symmetric (periodic) convention
    // cos(2π·i/(N-1)) so the coherent gain equals the window mean.
    function besselI0(x) {
      // Modified Bessel function of the first kind, order 0 (series expansion).
      let sum = 1, term = 1, m = 0;
      const x2 = (x * x) / 4;
      while (m < 100) {
        term *= x2 / ((m + 1) * (m + 1));
        sum += term;
        if (Math.abs(term) < 1e-15) break;
        m++;
      }
      return sum;
    }

    const FFT_WINDOWS = {
      rect: { enbw: 1.00, create: N => { const w = new Float64Array(N); w.fill(1); return w; } },
      hann: {
        enbw: 1.50,
        create: N => {
          const w = new Float64Array(N);
          for (let i = 0; i < N; i++) w[i] = 0.5 * (1 - Math.cos((2 * Math.PI * i) / (N - 1)));
          return w;
        },
      },
      hamming: {
        enbw: 1.36,
        create: N => {
          const w = new Float64Array(N);
          for (let i = 0; i < N; i++) w[i] = 0.54 - 0.46 * Math.cos((2 * Math.PI * i) / (N - 1));
          return w;
        },
      },
      blackman: {
        enbw: 1.73,
        create: N => {
          const w = new Float64Array(N);
          for (let i = 0; i < N; i++) {
            w[i] = 0.42 - 0.5 * Math.cos((2 * Math.PI * i) / (N - 1))
              + 0.08 * Math.cos((4 * Math.PI * i) / (N - 1));
          }
          return w;
        },
      },
      blackmanHarris: {
        enbw: 2.00,
        create: N => {
          const w = new Float64Array(N);
          for (let i = 0; i < N; i++) {
            w[i] = 0.35875 - 0.48829 * Math.cos((2 * Math.PI * i) / (N - 1))
              + 0.14128 * Math.cos((4 * Math.PI * i) / (N - 1))
              - 0.01168 * Math.cos((6 * Math.PI * i) / (N - 1));
          }
          return w;
        },
      },
      flattop: {
        enbw: 3.77,
        create: N => {
          const w = new Float64Array(N);
          for (let i = 0; i < N; i++) {
            w[i] = 0.21557895 - 0.41663158 * Math.cos((2 * Math.PI * i) / (N - 1))
              + 0.277263158 * Math.cos((4 * Math.PI * i) / (N - 1))
              - 0.083578947 * Math.cos((6 * Math.PI * i) / (N - 1))
              + 0.006947368 * Math.cos((8 * Math.PI * i) / (N - 1));
          }
          return w;
        },
      },
      kaiser: {
        enbw: 2.00, // β=8.6 ≈ Blackman-Harris stopband behavior
        create: N => {
          const beta = 8.6, i0b = besselI0(beta);
          const w = new Float64Array(N);
          for (let i = 0; i < N; i++) {
            const x = (2 * i) / (N - 1) - 1; // -1 .. 1
            w[i] = besselI0(beta * Math.sqrt(Math.max(0, 1 - x * x))) / i0b;
          }
          return w;
        },
      },
    };

    function getWindow(name) {
      return FFT_WINDOWS[name] || FFT_WINDOWS.hann;
    }

    // ===================== FFT Computation =====================
    function nextPowerOf2(n) {
      if (n < 2) return 2;
      let p = 1;
      while (p < n) p <<= 1;
      return p;
    }

    function detectSampleRate(rows, timeColumn) {
      // Returns { sampleRate, confidence: 'high'|'low'|'unknown', method }
      let dateCount = 0, numericCount = 0, totalDelta = 0, deltaCount = 0;
      let prevDate = null, prevNumeric = null;
      const deltas = [];
      const maxSamples = Math.min(rows.length, 200);
      for (let i = 0; i < maxSamples; i++) {
        const val = rows[i][timeColumn];
        if (val instanceof Date) {
          dateCount++;
          if (prevDate !== null) {
            const delta = (val - prevDate) / 1000;
            if (delta > 0) { totalDelta += delta; deltaCount++; deltas.push(delta); }
          }
          prevDate = val;
        } else if (typeof val === 'number' && Number.isFinite(val)) {
          numericCount++;
          if (prevNumeric !== null) {
            const delta = val - prevNumeric;
            if (delta > 0) { totalDelta += delta; deltaCount++; deltas.push(delta); }
          }
          prevNumeric = val;
        } else if (val !== null && val !== undefined) {
          const n = Number(val);
          if (Number.isFinite(n)) {
            numericCount++;
            if (prevNumeric !== null) {
              const delta = n - prevNumeric;
              if (delta > 0) { totalDelta += delta; deltaCount++; deltas.push(delta); }
            }
            prevNumeric = n;
          }
        }
      }
      if (deltaCount > 0) {
        const avgDelta = totalDelta / deltaCount;
        const sr = 1 / avgDelta;
        let variance = 0;
        for (let i = 0; i < deltas.length; i++) variance += (deltas[i] - avgDelta) ** 2;
        const cv = Math.sqrt(variance / deltas.length) / avgDelta;
        const confidence = cv < 0.05 ? 'high' : cv < 0.3 ? 'low' : 'unknown';
        const method = dateCount > 0 ? 'date' : 'numeric';
        return { sampleRate: sr, confidence, method };
      }
      return { sampleRate: 1, confidence: 'unknown', method: 'fallback' };
    }

    // Frequency-unit conversion factors from Hz: 1 Hz = 2π rad/s = 360 deg/s = 60 rpm
    const FREQ_UNIT_FACTORS = {
      'Hz': 1,
      'rad/s': 2 * Math.PI,
      'deg/s': 360,
      'rpm': 60,
    };

    function getFreqUnitFactor(unit) {
      return FREQ_UNIT_FACTORS[unit] ?? 1;
    }

    function convertFreqUnit(freqs, unit) {
      const factor = getFreqUnitFactor(unit);
      if (factor === 1) return freqs;
      const result = new Float64Array(freqs.length);
      for (let i = 0; i < freqs.length; i++) result[i] = freqs[i] * factor;
      return result;
    }

    function computeFFT(rows, varName, startIdx, endIdx, sampleRate, windowName) {
      // Extract non-null values from the selected range
      const rawValues = [];
      for (let i = startIdx; i < endIdx && i < rows.length; i++) {
        const val = rows[i][varName];
        if (val !== null && val !== undefined && Number.isFinite(Number(val))) {
          rawValues.push(Number(val));
        }
      }

      if (rawValues.length < 2) return null;

      // Determine FFT size: next power of 2
      const fftSize = nextPowerOf2(rawValues.length);
      const win = getWindow(windowName || 'hann');
      const window = win.create(rawValues.length);

      // Compute coherent gain for amplitude compensation
      let windowSum = 0;
      for (let i = 0; i < rawValues.length; i++) windowSum += window[i];
      const coherentGain = windowSum / rawValues.length;

      const padded = new Float64Array(fftSize);
      for (let i = 0; i < rawValues.length; i++) {
        padded[i] = rawValues[i] * window[i];
      }

      const rawMagnitudes = FourierTransform.rfft(padded);
      const numBins = rawMagnitudes.length;

      // Compensate for window coherent gain
      const magnitudes = new Float64Array(numBins);
      for (let i = 0; i < numBins; i++) {
        magnitudes[i] = rawMagnitudes[i] / coherentGain;
      }

      // Build correct frequency axis: f[i] = i * sampleRate / fftSize
      const binResolution = sampleRate / fftSize;
      const freqs = new Float64Array(numBins);
      for (let i = 0; i < numBins; i++) {
        freqs[i] = i * binResolution;
      }

      return {
        magnitudes: magnitudes,
        freqs: freqs,
        numBins: numBins,
        fftSize: fftSize,
        dataLength: rawValues.length,
        binResolution: binResolution,
        windowName: windowName || 'hann',
        enbw: win.enbw,
        coherentGain: coherentGain,
      };
    }

    // Averaged FFT: split the range into 50%-overlapping segments and combine spectra.
    //  - 'linear' : arithmetic mean of segment magnitudes (noise power averaging)
    //  - 'exp'    : exponentially-weighted moving average (alpha = 0.3), weights recent segments
    //  - 'peak'   : max-hold — element-wise maximum across segments (captures transients/spurs)
    function computeAveragedFFT(rows, varName, startIdx, endIdx, sampleRate, windowName, averaging) {
      const rawValues = [];
      for (let i = startIdx; i < endIdx && i < rows.length; i++) {
        const val = rows[i][varName];
        if (val !== null && val !== undefined && Number.isFinite(Number(val))) {
          rawValues.push(Number(val));
        }
      }
      const total = rawValues.length;
      if (total < 2) return null;

      const mode = averaging || 'none';
      if (mode === 'none') {
        return computeFFT(rows, varName, startIdx, endIdx, sampleRate, windowName);
      }

      // Segment layout: segment length ~ half the range (≥64), 50% overlap, max 32 segments.
      const baseN = nextPowerOf2(total);
      const segLen = Math.max(64, Math.min(baseN, Math.floor(total / 2)));
      const hop = Math.max(1, Math.floor(segLen / 2));
      const MAX_SEGMENTS = 32;
      const K = Math.min(MAX_SEGMENTS, Math.floor((total - segLen) / hop) + 1);
      if (K < 2) {
        // Not enough data to split meaningfully — fall back to a single FFT
        return computeFFT(rows, varName, startIdx, endIdx, sampleRate, windowName);
      }

      const win = getWindow(windowName || 'hann');
      const window = win.create(segLen);
      let windowSum = 0;
      for (let i = 0; i < segLen; i++) windowSum += window[i];
      const coherentGain = windowSum / segLen;

      const fftSize = nextPowerOf2(segLen);
      const numBins = fftSize / 2 + 1; // rfft positive-frequency bins
      const freqs = new Float64Array(numBins);
      for (let i = 0; i < numBins; i++) freqs[i] = i * (sampleRate / fftSize);

      const spectrumOf = (off) => {
        const padded = new Float64Array(fftSize);
        for (let i = 0; i < segLen; i++) padded[i] = rawValues[off + i] * window[i];
        const mags = FourierTransform.rfft(padded);
        for (let i = 0; i < numBins; i++) mags[i] = mags[i] / coherentGain;
        return mags;
      };

      let magnitudes;
      if (mode === 'peak') {
        magnitudes = new Float64Array(numBins).fill(-Infinity);
        for (let s = 0; s < K; s++) {
          const mags = spectrumOf(s * hop);
          for (let b = 0; b < numBins; b++) if (mags[b] > magnitudes[b]) magnitudes[b] = mags[b];
        }
      } else if (mode === 'exp') {
        const alpha = 0.3;
        let avg = null;
        for (let s = 0; s < K; s++) {
          const mags = spectrumOf(s * hop);
          if (avg === null) { avg = mags; }
          else for (let b = 0; b < numBins; b++) avg[b] = alpha * mags[b] + (1 - alpha) * avg[b];
        }
        magnitudes = avg;
      } else { // 'linear'
        const acc = new Float64Array(numBins);
        for (let s = 0; s < K; s++) {
          const mags = spectrumOf(s * hop);
          for (let b = 0; b < numBins; b++) acc[b] += mags[b];
        }
        magnitudes = new Float64Array(numBins);
        for (let b = 0; b < numBins; b++) magnitudes[b] = acc[b] / K;
      }

      return {
        magnitudes: magnitudes,
        freqs: freqs,
        numBins: numBins,
        fftSize: fftSize,
        dataLength: total,
        binResolution: sampleRate / fftSize,
        windowName: windowName || 'hann',
        enbw: win.enbw,
        coherentGain: coherentGain,
        averaging: mode,
        segments: K,
      };
    }

    function autoDetectBaseFreq(magnitudes, freqs, sampleRate, fftSize) {
      // Fundamental detection via harmonic support scoring.
      // Score = sum of significant harmonic peak magnitudes aligned with h·f0.
      // Only harmonics that are themselves significant local maxima count, so
      // missing harmonics (e.g. even harmonics of a square wave) are NOT penalized,
      // and the true fundamental wins because its own peak is the strongest.
      if (!magnitudes || magnitudes.length < 3) return { freq: sampleRate / fftSize, confidence: 'unknown' };

      const binResolution = sampleRate / fftSize;

      // Find all local maxima (skip DC at index 0)
      let maxMag = 0;
      const peaks = [];
      for (let i = 1; i < magnitudes.length - 1; i++) {
        if (magnitudes[i] > magnitudes[i - 1] && magnitudes[i] > magnitudes[i + 1]) {
          peaks.push({ index: i, mag: magnitudes[i], freq: freqs[i] });
          if (magnitudes[i] > maxMag) maxMag = magnitudes[i];
        }
      }

      if (peaks.length === 0) return { freq: binResolution, confidence: 'unknown' };

      const noiseFloor = maxMag * 0.1;
      const sigPeaks = peaks.filter(p => p.mag >= noiseFloor);

      if (sigPeaks.length === 0) {
        const best = peaks.reduce((a, b) => a.mag > b.mag ? a : b);
        return { freq: best.freq, confidence: 'low' };
      }

      // Single significant peak → it is the fundamental (no harmonics to disambiguate)
      if (sigPeaks.length === 1) {
        return { freq: sigPeaks[0].freq, confidence: 'low', harmonicCount: 1 };
      }

      const sigIndex = new Set(sigPeaks.map(p => p.index));
      const nyquist = sampleRate / 2;
      let bestCandidate = null, bestScore = -Infinity;

      for (const peak of sigPeaks) {
        const f0 = peak.freq;
        if (f0 < binResolution * 0.5) continue;
        let score = peak.mag; // h = 1 (the candidate itself)
        let harmonicCount = 1;
        for (let h = 2; h <= 20; h++) {
          const harmonicFreq = h * f0;
          if (harmonicFreq > nyquist * 0.95) break;
          const center = Math.round(harmonicFreq / binResolution);
          if (center >= magnitudes.length) break;
          // Search ±5 bins for a significant harmonic peak (f0 may be off-bin)
          const lo = Math.max(1, center - 5), hi = Math.min(magnitudes.length - 1, center + 5);
          for (let b = lo; b <= hi; b++) {
            if (sigIndex.has(b)) {
              score += magnitudes[b];
              harmonicCount++;
              break;
            }
          }
        }
        // Max harmonic support wins; tie-break toward lower frequency
        if (score > bestScore || (score === bestScore && f0 < bestCandidate.freq)) {
          bestScore = score;
          bestCandidate = { freq: f0, confidence: harmonicCount >= 2 ? 'high' : 'low', harmonicCount };
        }
      }

      if (bestCandidate) return bestCandidate;
      const best = sigPeaks.reduce((a, b) => a.mag > b.mag ? a : b);
      return { freq: best.freq, confidence: 'low' };
    }

    // ===================== Auto Measurements =====================
    // Computes harmonic-quality metrics from a Vpk magnitude spectrum.
    // All ratios are unit-invariant, so this runs on the raw spectrum
    // (before amplitude-unit / display transforms).
    function computeMeasurements(magnitudes, freqs, sampleRate, fftSize, baseFreq) {
      const numBins = magnitudes.length;
      if (numBins < 4 || !baseFreq || baseFreq <= 0) return null;
      const binRes = sampleRate / fftSize;

      // Find the strongest bin within ±5 of a target bin (handles off-bin f0 / leakage).
      // f0 may be quantized to a bin, so harmonic drift grows with h (~0.5 bin · h).
      const peakNear = (center) => {
        let best = center, bestMag = -Infinity;
        const lo = Math.max(1, center - 5), hi = Math.min(numBins - 1, center + 5);
        for (let b = lo; b <= hi; b++) {
          if (magnitudes[b] > bestMag) { bestMag = magnitudes[b]; best = b; }
        }
        return best;
      };

      const f0Bin = peakNear(Math.round(baseFreq / binRes));
      if (f0Bin <= 0 || f0Bin >= numBins) return null;

      const m1 = magnitudes[f0Bin];
      if (!Number.isFinite(m1) || m1 <= 0) return null;

      const nyquist = sampleRate / 2;
      const harmonics = [];
      let thdSq = 0;
      for (let h = 2; h <= 50; h++) {
        const hf = h * baseFreq;
        if (hf > nyquist) break;
        const bin = peakNear(Math.round(hf / binRes));
        if (bin <= 0 || bin >= numBins) break;
        const mh = magnitudes[bin];
        if (Number.isFinite(mh) && mh > 0) {
          harmonics.push({ h, freq: hf, bin, mag: mh });
          thdSq += mh * mh;
        }
      }

      const thdRatio = Math.sqrt(thdSq) / m1;
      const thdPct = thdRatio * 100;
      const thdDb = 20 * Math.log10(thdRatio);

      // THD+N / SINAD: total power excluding DC and the fundamental's main-lobe
      // notch (±5 bins), so window leakage of the carrier is not counted as distortion.
      let totalPower = 0;
      for (let i = 1; i < numBins; i++) {
        if (i >= f0Bin - 5 && i <= f0Bin + 5) continue;
        const m = magnitudes[i];
        if (Number.isFinite(m)) totalPower += m * m;
      }
      const thdnRatio = totalPower > 0 ? Math.sqrt(totalPower) / m1 : 0;
      const thdnPct = thdnRatio * 100;
      const thdnDb = thdnRatio > 0 ? 20 * Math.log10(thdnRatio) : -Infinity;
      const sinadDb = thdnRatio > 0 ? -20 * Math.log10(thdnRatio) : Infinity;

      // Noise floor / SNR / SFDR: exclude signal bins (±6 bins around components)
      const excluded = new Uint8Array(numBins);
      excluded[0] = 1; // DC
      const markExcluded = (bin) => {
        const lo = Math.max(1, bin - 6), hi = Math.min(numBins - 1, bin + 6);
        for (let i = lo; i <= hi; i++) excluded[i] = 1;
      };
      markExcluded(f0Bin);
      for (const h of harmonics) markExcluded(h.bin);

      let noisePower = 0, noiseCount = 0;
      let maxSpur = 0, maxSpurFreq = 0;
      for (let i = 1; i < numBins; i++) {
        if (excluded[i]) continue;
        const m = magnitudes[i];
        if (!Number.isFinite(m)) continue;
        noisePower += m * m;
        noiseCount++;
        if (m > maxSpur) { maxSpur = m; maxSpurFreq = freqs[i]; }
      }
      const noiseRms = noiseCount > 0 ? Math.sqrt(noisePower / noiseCount) : 0;
      const snrDb = noiseRms > 0 ? 20 * Math.log10(m1 / noiseRms) : Infinity;
      const sfdrDb = maxSpur > 0 ? 20 * Math.log10(m1 / maxSpur) : Infinity;
      const noiseFloorDb = noiseRms > 0 ? 20 * Math.log10(noiseRms / m1) : -Infinity;

      return {
        fundamental: { freq: baseFreq, mag: m1, bin: f0Bin },
        harmonics: harmonics,
        thd: { pct: thdPct, db: thdDb },
        thdn: { pct: thdnPct, db: thdnDb },
        sinad: sinadDb,
        snr: snrDb,
        sfdr: sfdrDb,
        noiseFloor: noiseFloorDb,
        maxSpur: { freq: maxSpurFreq, mag: maxSpur },
      };
    }
