// Plotter module: file-parse.js
// Generated by modularization of index.html inline script.

    dayjs.extend(dayjs_plugin_customParseFormat);
    const EXCEL_EPOCH = dayjs('1899-12-30');

    function excelSerialToDate(serial) {
      const adjustedSerial = serial >= 61 ? Math.floor(serial) - 1 : Math.floor(serial);
      const date = EXCEL_EPOCH.add(adjustedSerial, 'day');
      const fractionalDay = serial - Math.floor(serial);
      const milliseconds = Math.round(fractionalDay * 24 * 60 * 60 * 1000);
      return date.add(milliseconds, 'millisecond').toDate();
    }

    const TIME_FORMATS = [
      'YYYY-MM-DDTHH:mm:ssZ', 'YYYY-MM-DDTHH:mm:ss', 'YYYY-MM-DDTHH:mm:ss.SSSZ',
      'YYYY-MM-DDTHH:mm:ss.SSS', 'YYYY-MM-DD', 'DD/MM/YYYY', 'MM/DD/YYYY',
      'YYYY/MM/DD', 'YYYY-MM-DD HH:mm:ss', 'DD/MM/YYYY HH:mm',
      'MM/DD/YYYY HH:mm', 'YYYY/MM/DD HH:mm:ss', 'YYYY-MM-DD HH:mm',
      'YYYY/MM/DD HH:mm', 'MM-DD-YYYY HH:mm A', 'MM-DD-YYYY hh:mm A',
      'DD-MM-YYYY HH:mm', 'DD-MM-YYYY HH:mm:ss',
      'YYYY年M月D日 HH时mm分', 'YYYY年M月D日 HH时mm分ss秒', 'YYYY年M月D日',
      'YYYYMMDDHHmmss', 'YYYYMMDDHHmm', 'YYYYMMDD',
      'YYYY-MM-DDTHHmmss', 'YYYY-MM-DDTHHmm',
    ];

    function parseTime(value) {
      if (typeof value === 'number') {
        if (!Number.isFinite(value) || value <= 0) return null;
        if (value >= 1) return excelSerialToDate(value);
        return null;
      }
      const trimmed = String(value).trim();
      if (trimmed === '') return null;

      // Handle "YYYY-MM-DD HH:mm:ss NNNms" format
      const msMatch = trimmed.match(/^(\d{4}-\d{2}-\d{2}\s+\d{1,2}:\d{2}:\d{2})\s+(\d{1,3})\s*ms$/i);
      if (msMatch) {
        const d = dayjs(msMatch[1]);
        if (d.isValid()) {
          return d.add(parseInt(msMatch[2], 10), 'millisecond').toDate();
        }
      }

      const native = dayjs(trimmed);
      if (native.isValid()) return native.toDate();
      for (const fmt of TIME_FORMATS) {
        const p = dayjs(trimmed, fmt, true);
        if (p.isValid()) return p.toDate();
      }
      for (const fmt of TIME_FORMATS) {
        const p = dayjs(trimmed, fmt, false);
        if (p.isValid()) return p.toDate();
      }
      return null;
    }

    function isTimeString(value) {
      return parseTime(value) !== null;
    }


    function detectBinaryColumns(headers, rows, timeColumn) {
      const cols = new Set();
      const bits = new Map();

      for (const h of headers) {
        if (h === timeColumn) continue;

        let maxVal = 0;
        let isPositiveInt = true;
        let hasValue = false;

        for (const row of rows) {
          const v = row[h];
          if (v === null || v === undefined) continue;
          const n = Number(v);
          hasValue = true;
          if (!Number.isInteger(n) || n < 0) {
            isPositiveInt = false;
            break;
          }
          if (n > maxVal) maxVal = n;
        }

        if (hasValue && isPositiveInt && maxVal < 65536) {
          cols.add(h);
          bits.set(h, maxVal <= 255 ? 8 : 16);
        }
      }

      return { cols, bits };
    }

    function detectColumnFormat(column, rows) {
      const sampleSize = Math.min(rows.length, 10);
      const validDates = [];
      for (let i = 0; i < sampleSize; i++) {
        const val = rows[i]?.[column];
        if (val != null && val !== '') {
          const d = parseTime(String(val));
          if (d) validDates.push(d);
        }
      }
      if (validDates.length === 0) return 'unknown';
      const hasTime = validDates.some(d => d.getHours() !== 0 || d.getMinutes() !== 0 || d.getSeconds() !== 0);
      const hasDateRange = validDates.length > 1 && validDates.some(d => d.getDate() !== validDates[0].getDate());
      if (hasTime && hasDateRange) return 'datetime';
      if (hasTime) return 'time';
      return 'date';
    }

    // ===================== Data Parser =====================
    function normalizeValue(value) {
      if (value == null) return null;
      if (value instanceof Date) return value;
      if (typeof value === 'number') return value;
      if (typeof value === 'string') {
        const t = value.trim();
        if (t === '') return null;
        const n = Number(t);
        if (!Number.isNaN(n)) return n;
        return t;
      }
      return null;
    }

    function processRows(headers, rawRows, timeColumn) {
      return rawRows.map(raw => {
        const row = {};
        for (const h of headers) {
          const val = raw[h];
          if (h === timeColumn && val != null && val !== '') {
            const parsed = parseTime(String(val));
            row[h] = parsed ?? normalizeValue(val);
          } else {
            row[h] = normalizeValue(val);
          }
        }
        return row;
      });
    }

    function readFileAsArrayBuffer(file) {
      return new Promise((resolve, reject) => {
        const r = new FileReader();
        r.onload = () => resolve(r.result);
        r.onerror = () => reject(new Error(t('read_failed')));
        r.readAsArrayBuffer(file);
      });
    }

    function readFileAsText(file) {
      return new Promise((resolve, reject) => {
        const r = new FileReader();
        r.onload = () => resolve(r.result);
        r.onerror = () => reject(new Error(t('read_failed')));
        r.readAsText(file);
      });
    }

    function splitCSVLine(line, sep) {
      if (!line.includes('"')) return line.split(sep).map(f => f.trim());
      const fields = [];
      let field = '', inQuotes = false, i = 0;
      while (i < line.length) {
        const ch = line[i];
        if (inQuotes) {
          if (ch === '"') {
            if (i + 1 < line.length && line[i + 1] === '"') { field += '"'; i++; }
            else { inQuotes = false; }
          } else { field += ch; }
        } else {
          if (ch === '"') { inQuotes = true; }
          else if (ch === sep) { fields.push(field.trim()); field = ''; i++; continue; }
          else { field += ch; }
        }
        i++;
      }
      fields.push(field.trim());
      return fields;
    }

    function detectSeparator(sample) {
      const lines = sample.split('\n').filter(l => l.trim() !== '');
      if (lines.length === 0) return ',';
      const comma = (lines[0].match(/,/g) || []).length;
      const semi = (lines[0].match(/;/g) || []).length;
      return semi > comma ? ';' : ',';
    }

    async function parseCSV(file) {
      const buffer = await readFileAsArrayBuffer(file);
      let text;
      try {
        // 优先尝试 UTF-8，遇到非法序列则抛异常
        const decoder = new TextDecoder('utf-8', { fatal: true });
        text = decoder.decode(new Uint8Array(buffer));
      } catch (e) {
        // 回退到 GB18030（兼容 GBK、GB2312），解决中文编码乱码
        try {
          const decoder = new TextDecoder('gb18030', { fatal: false });
          text = decoder.decode(new Uint8Array(buffer));
        } catch (e2) {
          // 最终兜底：UTF-8 非严格模式
          const decoder = new TextDecoder('utf-8', { fatal: false });
          text = decoder.decode(new Uint8Array(buffer));
        }
      }
      const sep = detectSeparator(text);
      const lines = text.split('\n').filter(l => l.trim() !== '');
      if (lines.length === 0) return { headers: [], rawRows: [], rows: [], timeColumn: '', timeFormat: 'unknown' };
      const headers = splitCSVLine(lines[0], sep);
      const rawRows = [];
      const sampleRows = []; // only first 10 rows for time format detection
      for (let i = 1; i < lines.length; i++) {
        const fields = splitCSVLine(lines[i], sep);
        const row = {};
        for (let j = 0; j < headers.length; j++) {
          row[headers[j]] = normalizeValue(j < fields.length ? fields[j] : '');
        }
        rawRows.push(row);
        if (i <= 10) sampleRows.push(row); // rows 1-10 (first 10 data rows)
      }
      const timeColumn = headers[0] || '';
      const timeFormat = detectColumnFormat(timeColumn, sampleRows);
      return { headers, rawRows, rows: processRows(headers, rawRows, timeColumn), timeColumn, timeFormat };
    }

    async function parseExcel(file) {
      const buffer = await readFileAsArrayBuffer(file);
      const workbook = XLSX.read(new Uint8Array(buffer), { type: 'array' });
      const sheetName = workbook.SheetNames[0];
      if (!sheetName) return { headers: [], rows: [], timeColumn: '', timeFormat: 'unknown' };
      const sheet = workbook.Sheets[sheetName];
      const rawRowsRaw = XLSX.utils.sheet_to_json(sheet, { defval: '' });
      if (rawRowsRaw.length === 0) return { headers: [], rawRows: [], rows: [], timeColumn: '', timeFormat: 'unknown' };
      const headers = Object.keys(rawRowsRaw[0]);
      // Merge normalize into single pass, collect sample for time format detection
      const rawRows = [];
      const sampleRows = [];
      for (let i = 0; i < rawRowsRaw.length; i++) {
        const row = {};
        for (const h of headers) row[h] = normalizeValue(rawRowsRaw[i][h]);
        rawRows.push(row);
        if (i < 10) sampleRows.push(row);
      }
      const timeColumn = headers[0] || '';
      const timeFormat = detectColumnFormat(timeColumn, sampleRows);
      return { headers, rawRows, rows: processRows(headers, rawRows, timeColumn), timeColumn, timeFormat };
    }

    async function parseFile(file) {
      const name = file.name.toLowerCase();
      if (name.endsWith('.csv') || name.endsWith('.log') || name.endsWith('.txt')) return parseCSV(file);
      if (name.endsWith('.xls') || name.endsWith('.xlsx')) return parseExcel(file);
      throw new Error(t('unsupported_format') + file.name);
    }
