// Plotter module: i18n.js
// Generated by modularization of index.html inline script.

    // ===================== I18N =====================
    const I18N = {
      zh: {
        import: '选择文件',
        theme_light: '明亮',
        theme_dark: '黑暗',
        theme_toggle_title: '切换主题',
        drop_hint: '释放文件以导入',
        empty_title: '拖放或点击导入数据文件',
        empty_desc: '支持 CSV、Excel (.xls, .xlsx)、日志 (.log, .txt) 格式',
        select_file: '选择文件',
        var_select: '变量选择',
        search_placeholder: '搜索变量…',
        deselect_all: '取消选择',
        var_count: '个变量',
        max_limit: '（最多 {n} 个）',
        no_match: '无匹配变量',
        time_series: '时序图',
        xy_plot: 'XY图',
        xyz_plot: 'XYZ图',
        merged: '合并',
        separate: '分图',
        auto_scale: '自适应',
        reset_zoom: '图像复位',
        mode_ts: '时序图',
        mode_xy: 'XY 散点图',
        mode_xyz: 'XYZ 3D图',
        msg_select_var: '请选择要绘制的变量',
        msg_xy_need: 'XY模式需要至少2个变量',
        msg_xyz_need: 'XYZ模式需要至少3个变量',
        msg_var_limit: '{mode}最多选择 {n} 个变量',
        unsupported_format: '不支持的文件格式：',
        read_failed: '读取文件失败',
        parse_failed: '文件解析失败',
        new_version: '新版本 {v} 可用，点击前往下载',
        bin_toggle_dec: '切换至十进制',
        bin_toggle_bin: '切换至二进制',
        bin_disabled: '仅在时序图分图模式下可用',
        fft_plot: 'FFT分析',
        fft_freq_unit: '频率单位',
        fft_y_axis: 'Y轴',
        fft_x_axis: 'X轴',
        fft_apply: '应用',
        fft_per_unit: '标幺值',
        fft_physical: '物理值',
        fft_linear: '笛卡尔坐标',
        fft_log: '对数坐标',
        fft_db: 'dB',
        fft_window: '窗函数',
        win_rect: '矩形',
        win_hann: 'Hann',
        win_hamming: 'Hamming',
        win_blackman: 'Blackman',
        win_blackman_harris: 'Blackman-Harris',
        win_flattop: '平顶',
        win_kaiser: 'Kaiser',
        fft_avg: '平均',
        avg_none: '单次',
        avg_linear: '线性',
        avg_exp: '指数',
        avg_peak: '峰值保持',
        fft_amp: '幅度',
        amp_pk: '峰值',
        amp_rms: '有效值',
        amp_rms_label: 'Vrms',
        meas_f0: 'f₀',
        meas_noise: '噪底',
        msg_fft_need: 'FFT模式需要选择1个变量',
        msg_fft_no_data: '所选范围内有效数据不足，无法进行FFT分析',
        mode_fft: 'FFT 频谱分析',
        lang_label: 'EN',
        lang_title: 'Switch to English',
      },
      en: {
        import: 'Select File',
        theme_light: 'Light',
        theme_dark: 'Dark',
        theme_toggle_title: 'Toggle Theme',
        drop_hint: 'Drop file to import',
        empty_title: 'Drag & drop or click to import data',
        empty_desc: 'Supports CSV, Excel (.xls, .xlsx), Log (.log, .txt) formats',
        select_file: 'Select File',
        var_select: 'Variable Selection',
        search_placeholder: 'Search variables…',
        deselect_all: 'Deselect',
        var_count: 'variables',
        max_limit: '(Max {n})',
        no_match: 'No matching variables',
        time_series: 'Time Series',
        xy_plot: 'XY Plot',
        xyz_plot: 'XYZ 3D',
        merged: 'Merged',
        separate: 'Separate',
        auto_scale: 'Auto Scale',
        reset_zoom: 'Reset Zoom',
        mode_ts: 'Time Series',
        mode_xy: 'XY Scatter',
        mode_xyz: 'XYZ 3D Scatter',
        msg_select_var: 'Please select variables to plot',
        msg_xy_need: 'XY mode requires at least 2 variables',
        msg_xyz_need: 'XYZ mode requires at least 3 variables',
        msg_var_limit: '{mode} chart supports max {n} variables',
        unsupported_format: 'Unsupported file format: ',
        read_failed: 'Failed to read file',
        parse_failed: 'File parsing failed',
        new_version: 'New version {v} available, click to download',
        bin_toggle_dec: 'Switch to Decimal',
        bin_toggle_bin: 'Switch to Binary',
        bin_disabled: 'Only available in time-series separate mode',
        fft_plot: 'FFT Analysis',
        fft_freq_unit: 'Freq Unit',
        fft_y_axis: 'Y-Axis',
        fft_x_axis: 'X-Axis',
        fft_apply: 'Apply',
        fft_per_unit: 'Per-Unit',
        fft_physical: 'Physical',
        fft_linear: 'Linear',
        fft_log: 'Logarithmic',
        fft_db: 'dB',
        fft_window: 'Window',
        win_rect: 'Rect',
        win_hann: 'Hann',
        win_hamming: 'Hamming',
        win_blackman: 'Blackman',
        win_blackman_harris: 'Blackman-Harris',
        win_flattop: 'Flat-top',
        win_kaiser: 'Kaiser',
        fft_avg: 'Avg',
        avg_none: 'Single',
        avg_linear: 'Linear',
        avg_exp: 'Exponential',
        avg_peak: 'Peak Hold',
        fft_amp: 'Amplitude',
        amp_pk: 'Vpk',
        amp_rms: 'Vrms',
        amp_rms_label: 'Vrms',
        meas_f0: 'f₀',
        meas_noise: 'Noise Floor',
        msg_fft_need: 'FFT mode requires 1 variable selected',
        msg_fft_no_data: 'Not enough valid data in range for FFT analysis',
        mode_fft: 'FFT Spectrum',
        lang_label: 'CN',
        lang_title: '切换到中文',
      }
    };

    let currentLang = (() => {
      try {
        const saved = localStorage.getItem('plotter-lang');
        if (saved === 'en' || saved === 'zh') return saved;
      } catch (_) {}
      return navigator.language.startsWith('zh') ? 'zh' : 'en';
    })();

    function t(key, params) {
      let str = (I18N[currentLang] && I18N[currentLang][key]) || (I18N['zh'][key]) || key;
      if (params) {
        for (const [k, v] of Object.entries(params)) {
          str = str.replace(`{${k}}`, v);
        }
      }
      return str;
    }

    function setLanguage(lang) {
      if (!I18N[lang]) return;
      currentLang = lang;
      try { localStorage.setItem('plotter-lang', lang); } catch (_) {}
      updateStaticTexts();
      if (data) {
        saveZoomState();
        renderApp();
      }
    }

    function updateLangToggle() {
      const btn = document.getElementById('langToggle');
      if (btn) btn.title = t('lang_title');
    }

    function updateStaticTexts() {
      // Update static UI elements that exist when no data is loaded
      const langBtn = document.getElementById('langToggle');
      if (langBtn) langBtn.title = t('lang_title');
      const themeToggleEl = document.getElementById('themeToggle');
      if (themeToggleEl) themeToggleEl.title = t('theme_toggle_title');
      const importText = document.getElementById('importText');
      if (importText) importText.textContent = ' ' + t('import');
      const dragHint = document.getElementById('dragHint');
      if (dragHint) dragHint.textContent = t('drop_hint');
      const emptyH2 = document.getElementById('emptyTitle');
      if (emptyH2) emptyH2.textContent = t('empty_title');
      const emptyP = document.getElementById('emptyDesc');
      if (emptyP) emptyP.textContent = t('empty_desc');
      const emptyImportText = document.getElementById('emptyImportText');
      if (emptyImportText) emptyImportText.textContent = ' ' + t('select_file');
    }
